### ISSUE TITLE
Clarify Symprec

### ISSUE THREAD

**Issue by shyamd** [materialsproject/pymatgen#1141]
The comments in SpacegroupAnalyzer state that the default symprec is 1E-3, when it is really 1E-2 right now. It also suggests that loosely optimized structures should use a symprec of 1E-1, and this is the default in MP. 

Can we get some clarity on what the intended default **should** be? Also, should the defaults be switched around to be appropriate for loosely optimized structures and require the user to modify symprec for more 'precise' symmetry information.

**Comment by shyuep** [comment]
This has been discussed before. The default should be strict. In most instances, you want to err on the side of treating structures as different rather than treating them the same. Pymatgen is not meant to be a code for computational materials scientists. When people discuss symmetry of crystal structures, the precision of measured atomic distances is within 0.01A.
