### ISSUE TITLE
Extremely slow MinimumVIRENN analysis

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#1169]
## System

* Pymatgen version: 2018.4.20 -- 2018.5.22 (present)
* Python version: 3.6.5
* OS version: Issue occurs on Windows and Linux

## Summary

The `MinimumVIRENN` algorithm in `pymatgen.analysis.local_env` used to be quite fast, but a change was introduced in the 2018.4.20 release of Pymatgen that has caused it to be orders of magnitude slower and has not been fixed in the current 2018.5.22 release. Compared to `VoronoiNN`, the current implementation of `MinimumVIRENN` can be 100x slower or more. 

## Example code

```python
from pymatgen.io.cif import CifParser
from pymatgen.analysis.local_env import MinimumVIRENN, VoronoiNN
import time

site_idx = 0
parser = CifParser('test.cif')
structure = parser.get_structures()[0]

t0 = time.time()
nn_object = MinimumVIRENN()
neighbors = nn_object.get_nn_info(structure,site_idx)
t1 = time.time()-t0
print('VIRE: '+str(t1))

t0 = time.time()
nn_object = VoronoiNN()
neighbors = nn_object.get_nn_info(structure,site_idx)
t2 = time.time()-t0
print('Voronoi: '+str(t2))
```

Results:
VIRE: 4.755153179168701
Voronoi: 0.028443098068237305

## Files (if any)

Please see attached for the `test.cif` file used in this example. Change the .txt extension to .cif before use.
[test.txt](https://github.com/materialsproject/pymatgen/files/2087561/test.txt)

**Comment by arosen93** [comment]
Any ideas @computron? I noticed you have added a lot of nice changes to the `local_env` class lately. The [4.6.2018 version](https://pypi.org/project/pymatgen/2018.4.6/) is the last one that still works reasonably efficiently with the MinimumVIRENN algorithm.

**Comment by computron** [comment]
I haven’t touched MininumVIRENN, you might want to ask @nisse3000 as I think it’s his algorithm

**Comment by nisse3000** [comment]
Hello @arosen93,

I've had a look into the problem by using a pre-2018-04-20 version of pymatgen. What it made much faster was that the valences of all sites were predicted to be zero so that the ValenceIonicRadiusEvaluator didn't bother to use interpolated ionic radii based on the O'Keeffe data. It just set the radii to atomic radii to deal with this issue. The valences that I see now make mostly sense. Only, the one for H seems very weird to me.
C 1
C 2
H -1
Mg 2
O -2

But I guess the bottom line regarding the slow down is: the algorithm now does (much more) what you expect it to do. Maybe we should make it optional to use atomic radii instead of (interpolated) ionic radii to deal with zero valences in all sites. What's your take on this as a user?

**Comment by arosen93** [comment]
Hi @nisse3000,

Oh, wow. Yes that change does make it do much more what I thought it did. Those valences all seem appropriate except H like you said.

As a user, I think your suggestion is a good one. The current speed of the VIRENN algorithm makes it infeasible to use on a large database of materials (which, of course, is where automated approaches become essential). I think giving the user an option to use atomic radii, while not necessarily desirable compared to interpolated ionic radii, would be very helpful. Thanks for taking a look at this.

**Comment by computron** [comment]
I would suggest to separate out the process of getting valences and getting radii

There are a few ways to get valence in pymatgen, including the quite fast "get_oxi_state_by_guess" method. In addition, sometimes a user might already know the valence from some other means (e.g., from ICSD valence assignments). Rather than re-determining the valences with BVAnalyzer, you should be able to just use those valences you already have from some other means in order to use it. It would only be a couple lines of code to either (i) only evaluate the valences if not already set by some other means (e.g, if the sites in the strucutre don't already have oxidation states) or (ii) simply require the user to put in a structure with valence states in there (e.g., by pre-processing with BVAnalyzer, get_oxi_state_by_guess, or some other means) in order to get the radii.

Incidentally, we have been been doing a lot of tests of near neighbor algorithms and the new CrystalNN method we are developing seems to be doing considerably better than others, at least for typical metals / inorganic materials.

**Comment by computron** [comment]
Also, I am looking at VIRENN code now and am surprised there is a 10 Angstrom search radius for looking for neighbors. I've found that such large search radii can take time to compute. 

If I understand the algorithm correctly, you just care about neighbors within your atomic/ionic radius plus tolerance (usually will be on the order of 3-5 Angstroms). So you could just search for neighbors within that range instead of a 10 Angstrom radius which will speed things up a lot

**Comment by arosen93** [comment]
Thanks @computron. I think as a user (and given the name of the VIRE algorithm) I just assumed that pymatgen was somehow estimating the oxidation states if not provided but see now that it defaults to atomic radii instead. At the least, I think it'd be helpful to make that clearer in whatever way is most appropriate.

Yes, the 10 A radius seemed very odd to me. I'm not sure why it's so large but didn't want to change it. I'll modify that going forward. Thanks! And I look forward to checking out CrystalNN! Looks very interesting.

**Comment by computron** [comment]
Nevermind - the above about 10 Angstrom radius is not correct. But I do think you could start the algorithm which a much smaller radius (e.g. 7-8 Angstrom) and only increase it larger if necessary (automatically). For example, the code can increase the radius if no neighbors are found, or if the code (after finding the nearest neighbor) detects there is a chance for some ion to be greater than 7 Angstroms from the center and still fulfill the criteria of being a neighbor.

**Comment by mkhorton** [comment]
The main problem with VIRE right now is that BVAnalyzer is re-run for every site, which is very inefficient. This is a common problem with a lot of the NN classes. The [`_get_valences()`](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/analysis/local_env.py#L188) function is also not ideal because it has two nested try/excepts ... better would be to use AutoOxiStateTransformation (and making modifications to that if appropriate) than re-implementing this functionality in a private method in local_env
  * I agree with @computron that this behavior is ideally separated out (i.e. at the very least, if oxidation states are already present BVAnalyzer *should not* be run, and it would be good to be able to choose the oxidation-state decoration algorithm; again this could be added to AutoOxiStateTransformation)
  * I think `ValenceIonicRadiusEvaluator` should probably not be its own class anyway, and should be wrapped into the `MinimumVIRENN` class (it'll be a lot shorter/simpler if the transformation is used)

@arosen93 " I just assumed that pymatgen was somehow estimating the oxidation states if not provided but see now that it defaults to atomic radii instead. " -- yes, pymatgen is actually estimating oxidation states and using ionic radii based on that. I do think it's doing something weird if it doesn't know the oxidation state however, incorporating co-ordination numbers from VoronoiNN. @nisse3000 can you comment on this? Was this in the VIRE paper?

**Comment by mkhorton** [comment]
Closing since this was partly addressed in https://github.com/materialsproject/pymatgen/pull/1630 (Oct 2019, thanks @utf), still slow, but not as slow!
