### ISSUE TITLE
VoronoiNN causes Python to crash

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#1281]
Calling `pymatgen.analysis.local_env.VoronoiNN.get_voronoi_polyhedra()` on a structure obtained via `MPRester` is causing Python to crash. Note that Python itself is crashing, not just returning an error message.

The structure in question is: https://materialsproject.org/materials/mp-978085/. It is a relatively small primitive cell with only 4 sites.

## System

* Pymatgen version: 2018.9.12
* Python version: Tested on 3.6.2 and 3.7.0
* OS version: macOS 10.13.6 (High Sierra)

## Example code

```python
from pymatgen.analysis.local_env import VoronoiNN
from pymatgen.ext.matproj import MPRester

mpr = MPRester()
struct = mpr.get_structure_by_material_id('mp-978085')

voro = VoronoiNN()
voro.get_voronoi_polyhedra(struct, 2)  # sites 0, 1, and 3 work fine
```

## Error message

macOS crash reporter produces an error message saying:

```
malloc: *** error for object 0x1062909e8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Python quit unexpectedly.
```

![image](https://user-images.githubusercontent.com/1330638/45648928-b62f5100-ba7e-11e8-960d-70bb60e1458e.png)

This appears to be a memory allocation error. Obviously Python itself should not crash under any circumstances but I wonder if we can do something on our end to circumvent this issue.

**Comment by utf** [comment]
Looking at `VoronoiNN().get_voronoi_polyhedra()` in more detail. The code actually mentions the potential for a segfault to occur if the cutoff used is too small.

```python
        while True:
            try:
                neighbors = structure.get_sites_in_sphere(
                    center.coords, cutoff)
                neighbors = [i[0] for i in
                             sorted(neighbors, key=lambda s: s[1])]

                # Run the Voronoi tessellation
                qvoronoi_input = [s.coords for s in neighbors]
                voro = Voronoi(
                    qvoronoi_input)  # can give seg fault if cutoff is too small
                break

            except RuntimeError:
                if cutoff >= max_cutoff:
                    raise RuntimeError("Error in Voronoi neighbor finding; max "
                                       "cutoff exceeded")
                cutoff = min(cutoff * 2, max_cutoff + 0.001)
```

Increasing the cutoff in the above example actually fixes the error. It's not ideal that this is happening with the default cutoff. Is there some way to predict whether the cutoff will be too small and instead raise an error?

**Comment by mkhorton** [comment]
Yes, I did raise it at the scipy repo. No fix yet though :(

I don't really understand what specific set of conditions is causing this bug (hence the rather long bug report, because I couldn't find a more minimal example).

If you can find a sensible cutoff where this never happens, that would be ideal -- otherwise (as a temporary fix) I'm not sure if it might be possible to use multiprocessing, and run the Voronoi in a child process, so if it crashes it won't bring down the parent process?

**Comment by mkhorton** [comment]
@utf I tried the following snippet with a known bad array:

```
from scipy.spatial import Voronoi
import multiprocessing
def get_voronoi(arr):
    with multiprocessing.Pool(1) as pool:
        result = pool.apply_async(Voronoi, (arr, ))
        value = result.get(timeout=1)
    return value
```

This will raise a TimeoutError if the array is bad instead of completely crashing the parent process, so can be recovered from more gracefully.

Could you investigate if this approach could be integrated as a temporary fix, until the scipy bug is resolved, and submit a PR as appropriate?

**Comment by utf** [comment]
@mkhorton Nice idea. Will give it a go.

**Comment by utf** [comment]
I've implemented a version where this works nicely (e.g. it increases the timeout value/cutoff depending on the crash type) which actually correctly calculates the data for the difficult case I mentioned above.

Unfortunately, when I tried to use this with matminer to run over all the materials in the MP everything fell apart. Matminer already uses `Pool` to speed up featurization, and in the standard Python `multiprocessing` library Pools cannot create their own Pools :(.

I'm looking into the option of using `ThreadPool` in matminer but I think this might have a heavy toll on featurization time.

**Comment by mkhorton** [comment]
That's a shame about matminer, but from the pymatgen-point-of-view we can't really be responsible for other libraries that might also want to use multiprocessing, since we use multiprocessing elsewhere in pymatgen to speed up several operations.

That said, it does look like creating pools-of-pools might be possible. Could you use concurrent.futures for this instead? https://stackoverflow.com/a/17229030/637562

Thanks very much for trying this out btw. This Voronoi bug is holding up some other database building we're trying to do too, so it'd be really nice to get it fixed (we can't use CrystalNN as a default bonding strategy until this is resolved).

**Comment by utf** [comment]
I tried implementation a number of ideas based on your suggestion. All worked equally well at catching the python crash but also caused issues with `matminer`. Unfortunately, when you start a process from within another process (either through `ProcessPoolExecutor` or by hacking `multiprocessing.Pool` to spawn non-daemonic processes), you get a severe performance loss due to extra overhead, which I think must be cython's fault.

As an alternative, I tried setting the default cutoff to 13.0 instead of 10.0. Using this method I was able to process all 85,000 structures in the materials project database without a fatal segfault occurring.  Unfortunately, this also results in a slight increase in running time as more atoms will be considered.

The timings for how long it took the different approaches to process all 85,000 structures are:

```
Pool, default cutoff=8.0: 15 h 40 min
No Pool, default cutoff=13.0: 13 h 15 min
```

It seems like, for now, setting the default cutoff to 13 is a workable solution that is best for `pymatgen` and `matminer`. Unfortunately, this might not be robust to new materials being added to the MP database.

If you're happy to go down this route, I'll submit a pull request with the changes (I also fixed another bug which means that we can now get Voronoi polyhedra for all materials).
