### ISSUE TITLE
Search Pt, seemed got wrong result

### ISSUE THREAD

**Issue by fallleave001** [materialsproject/pymatgen#1357]
**Describe the bug**

When using api to search Pt crystalline, got the following:

[Structure Summary
Lattice
    abc : 2.8120017156650783 2.8120017104377606 2.81200171
 angles : 59.99999988751204 59.999999949004994 59.99999997242852
 volume : 15.722867111767158
      A : 2.43526492 0.0 1.40600086
      B : 0.81175497 2.29598978 1.40600086
      C : 0.0 0.0 2.81200171
PeriodicSite: Pt (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]]

The above structure for Pt seemed different with which got from http://rruff.geo.arizona.edu/AMS/amcsd.php.

**To Reproduce**
1. set api_key in yaml file
2. python code,
from pymatgen.ext.matproj import MPRester

with MPRester() as m:
    results = m.get_structures('Pt')
    print(results)

Thanks in advance for your kind response.

**Comment by mkhorton** [comment]
Hi @fallleave001, in what way does it seem wrong to you? They look correct. Note that the structure retrieved by the API is in a primitive setting and since Pt is a face-centered cubic crystal the lattice parameters in the primitive and conventional setting are not the same but are related by sqrt(2), so that the conventional lattice parameter computed by Materials Project is 2.812*sqrt(2) = 3.98 Å, which matches well (within normal calculation error) to the 3.9 Å values in the AMCSD.

Also, note we have a [discussion forum](https://discuss.materialsproject.org) on the Materials Project to discuss the data available on the Materials Project, so that's a good place to ask these sorts of questions. The pymatgen issues page is intended to report bugs in pymatgen itself.

**Comment by fallleave001** [comment]
@mkhorton , Thanks a lot. It's my fault to misunderstand it. Now It works well. Please close this issue.

**Comment by mkhorton** [comment]
You’re welcome!
