### ISSUE TITLE
pymatgen.io.aiida broken with aiida_core >= 1.0

### ISSUE THREAD

**Issue by ConradJohnston** [materialsproject/pymatgen#1432]
The [pymatgen.io.aiida](http://pymatgen.org/_modules/pymatgen/io/aiida.html) module is broken in AiiDA core v1.0 and onwards. 

This is due to the refactoring of AiiDA which breaks the import line:
https://github.com/materialsproject/pymatgen/blob/5f652417aa3a03214e8dfe726fc9747ed71f13e2/pymatgen/io/aiida.py#L21
The code falls through into the except block, setting the `aiida_loaded` flag to false and preventing any of the methods from being used. 

Should be straightforward to fix and happy to contribute a pull request, but it would be good to have some input as to whether it should be fixed. 

Within AiiDA core, it is now straightforward to convert to and from Pymatgen structure objects. Any fix would need to support AiiDA before and after v1.0, in principle. So alternatively, as AiiDA does these things, does it make sense to simply deprecate this function and, if you have AiiDA > v1.0, print a warning to this effect?

Would be great to hear your thoughts!

**Comment by shyuep** [comment]
I would say this depends entirely on the aiida developers. I would be fine with just deprecating this function and raising an error and pointing to the aiida package. Because there are no unittests written for pymatgen.io.aiida, we have no way of testing the functionality at all.

I will just completely deprecate this module. I will push a change shortly.

**Comment by ConradJohnston** [comment]
I think this is fine, but I defer to @sphuber .
