### ISSUE TITLE
Inconsistency btw SpacegroupAnalyzer & SpaceGroup

### ISSUE THREAD

**Issue by mt-huebsch** [materialsproject/pymatgen#1463]
Hello everyone,
I am a first-timer. Thank you for taking the time.
Best, Marie-Therese

**Describe the bug**
The symmetry operations returned by pymatgen.symmetry.analyzer SpacegroupAnalyzer.get_symmetry_operations() and pymatgen.symmetry.groups SpaceGroup.symmetry_ops do not agree.

**To Reproduce**

See here [bug_report.zip](https://github.com/materialsproject/pymatgen/files/3159722/bug_report.zip) or follow these steps:

0. Setup
```
import urllib.request
server_dir = "http://webbdcrista1.ehu.es/magndata/mcif/"
cif_file = "0.1.mcif"
urllib.request.urlretrieve(server_dir + cif_file, cif_file)
```
or download mcif here:
[http://webbdcrista1.ehu.es/magndata/index.php?index=0.1](url)

1. Init Structure and get_space_group_info 
```
import pymatgen
s = pymatgen.Structure.from_file( cif_file, primitive=True)

print( "Structure:")
print( s.get_space_group_info() )
```

2. get_space_group_info and operations using pymatgen.symmetry.analyzer
```
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
a = SpacegroupAnalyzer( s )
print( "\nAnalyzer:" )
print( a.get_space_group_symbol(), a.get_space_group_number() )
for op in a.get_symmetry_operations():
    print( op.as_xyz_string() )
```

3. Construct SpaceGroup from space_group_info obtained in (2.)
```
from pymatgen.symmetry.groups import SpaceGroup
g = SpaceGroup.from_int_number( s.get_space_group_info()[1] )

print( "\nSpaceGroup:" )
for op in g.symmetry_ops:
    print( op.as_xyz_string() )
```

*Output:*
```
Structure:
('Pnma', 62)

Analyzer:
Pnma 62
x, y, z
-x, -y, -z
-x+1/2, -y, z+1/2
x+1/2, y, -z+1/2

SpaceGroup:
x, y, z
-x+1/2, -y, z+1/2
x+1/2, -y+1/2, -z+1/2
-x, y+1/2, -z
-x, -y, -z
x-1/2, y, -z-1/2
-x-1/2, y-1/2, z-1/2
x, -y-1/2, z
```

One may use [http://www.cryst.ehu.es/cgi-bin/cryst/programs/checkgr.pl?tipog=gesp](url) to determine that step 3 correctly returns Pnma (No. 62) and step 2 returns P21/c (No. 14).

**Expected behavior**
a.get_symmetry_operations() and g.symmetry_ops should return the same spg elements.

**Additional info**
By some shallow digging I found that the Analyzer employs Togo senseis library, while SpaceGroup seems to use a preset json.

*ad step 2* pymatgen.symmetry.analyzer SpacegroupAnalyzer._get_symmetry(self) uses spglib.get_symmetry
*ad step 3* pymatgen.symmetry.groups.SpaceGroup uses SYMM_OPS = loadfn(os.path.join(os.path.dirname(__file__), "symm_ops.json"))

**Comment by mkhorton** [comment]
Welcome @mt-huebsch !

Regarding your bug, I'm not sure I can re-produce. If you look at the 0.1.mcif file, in the file itself we see the symmetry operations:

```
1 x,y,z,+1 
2 -x,y+1/2,-z,+1 
3 -x,-y,-z,+1 
4 x,-y+1/2,z,+1 
5 x+1/2,-y+1/2,-z+1/2,-1 
6 -x+1/2,-y,z+1/2,-1 
7 -x+1/2,y+1/2,z+1/2,-1 
8 x+1/2,y,-z+1/2,-1 
```

Or you can check [here](http://img.chem.ucl.ac.uk/sgp/large/062az1.htm) or Bilbao's GENPOS tool for Pnma.

This seems to be consistent with the output of the space group class.

If you list `a.get_symmetry_dataset()` (returning the dataset for Pnma from spglib), you'll see similar operations defined for Pnma.

The reason SpacegroupAnalyzer is giving different symmetry operations is ultimately because of what `spglib.get_symmetry()` returns, and this is actually taking into account the magnetic moments on your cell. If you remove the magnetic moments you get the correct answer as expected:

```
Analyzer:
Pnma 62
x, y, z
-x, -y, -z
-x+1/2, -y, z+1/2
x+1/2, y, -z+1/2
x+1/2, -y+1/2, -z+1/2
-x+1/2, y+1/2, z+1/2
-x, y+1/2, -z
x, -y+1/2, z
```

Note that spglib does not handle magnetic symmetry gracefully (it does not understand magnetic symmetry, but does try to take into account magnetic moments as scalars, so the information it reports is something more similar to exchange group symmetry I believe, though I don't have good documentation for this). In either case, spglib is correctly concluding that the magnetic moments impose a lower symmetry on the lattice while still reporting the correct crystallographic space group. I agree this is misleading. Hopefully spglib will natively support magnetic symmetry correctly one day.

**Comment by mt-huebsch** [comment]
Thank you for the quick and easy explanation @mkhorton!

It's a bit misleading that ```SpacegroupAnalyzer``` returns Pnma (No. 62) as an info while returning the reduced symmetry operations. I would expect the info also to correspond to the reduced (exchange group) symmetry then...

Anyways, I am glad there is a way to work around it easily by using ```SpaceGroup``` (and in general to be able to use this package). 

It seems elsewhere ```pymatgen``` neatly separates between magnetic space groups and space groups, e.g. by having  the two modules ```pymatgen.symmetry.groups``` and ```pymatgen.symmetry.maggroups``` (although they currently have different power). Hence in my view, one might consider to strictly keep the separation by not considering time reversal symmetry within ```pymatgen.symmetry.analyzer``` with ```PointGroupAnalyzer```, ```PointGroupOperations```, ```SpacegroupAnalyzer```, ```SpacegroupOperations```  and maybe adding ```MagSpacegroupAnalyzer```, ```MagSpacegroupOperations``` in the long run.

On a side note, I adapted this Transformation to apply a magnetic space group symmetry operation. It seems operate_magmom() is handling magnetic moments as axial vector, hence gracefully enough right?

```
from pymatgen.transformations.transformation_abc import AbstractTransformation
class ApplyMagSymmOpTransformation(AbstractTransformation):
  """ 
  Transformation to apply magnetic space group symmetry operation.
  """
  def __init__(self, mag_op, fractional=True, to_unit_cell=True):
    """ 
    Args:
      pymatgen.core.operations.MagSymmOp
    """
    self.mag_op = mag_op
    self.fractional= fractional
    self.to_unit_cell= to_unit_cell

  def apply_transformation(self, structure):
    # init new structure
    new_structure = structure.copy()
    # apply xyz op
    new_structure.apply_operation( self.mag_op, fractional=self.fractional )
    # back to unit cell
    new_structure.translate_sites( [ i for i, _ in enumerate(new_structure.sites)]  , [0,0,0] )
    # apply time rev symm
    new_magmom_list = []
    for site in new_structure.sites:
      new_magmom_list.append( self.mag_op.operate_magmom( site.properties["magmom"] ) ) 
    new_structure.add_site_property( "magmom", new_magmom_list )
    # return new structure
    return new_structure

  @property
  def is_one_to_many(self):
    return False

  @property
  def inverse(self):
    raise NotImplementedError()
```

Thank you!

**Comment by mkhorton** [comment]
> Hence in my view, one might consider to strictly keep the separation by not considering time reversal symmetry [...]

Yes, I agree. I think it would make more sense to remove the magnetic moment information entirely from the normal symmetry classes to reduce confusion.

The reason for the separation of the pymatgen classes is mostly historical: the `maggroups` module was only added relatively recently, and uses the dataset kindly provided by Stokes and Campbell, but the format of this data is slightly different to that of the regular crystallographic dataset we use. This is why the modules have slightly different (though similar) APIs.

Likewise, the reason the magnetic moment information is included in the SpacegroupAnalyzer is simply because spglib offers an interface for it, so pymatgen dutifully supplies the magnetic moments. However given that the output is confusing I think this should be disabled by default.

> It seems operate_magmom() is handling magnetic moments as axial vector

Yes, that's correct. You may also find `Structure. from_magnetic_spacegroup(...)` useful (note that the pip installation of pymatgen is missing the required magnetic symmetry data file, but this will be present in the next pymatgen release, or can be downloaded manually).

**Comment by mt-huebsch** [comment]
Thanks for the advise. I am sure it will come in handy.

One more thing, do **I** close the issue (or who)?

**Comment by mkhorton** [comment]
No problem. In general, you can close an issue if it's resolved, but let's leave it open for now until we make the change that was suggested to make the output of SpacegroupAnalyzer less misleading.
