### ISSUE TITLE
WulffShape Construction Not displaying Plot and Matplotlib Deprecation Warning

### ISSUE THREAD

**Issue by Leo3Lee** [materialsproject/pymatgen#1474]
**Describe the bug**
Dear pymatgen communities,

I am running a Si Wulff Shape Construction based on the excellent tutorial from https://matgenb.materialsvirtuallab.org/2017/04/03/Slab-generation-and-Wulff-shape.html

However, when running the code, no Wulff shape plot was displayed at the end, and a warning message related to Matplotlib deprecation also appeared.

**To Reproduce**

I used the exact same code from the tutorial
https://matgenb.materialsvirtuallab.org/2017/04/03/Slab-generation-and-Wulff-shape.html

**Expected behavior**
No Wulff plot displayed, and warning message appeared as 
/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:424: MatplotlibDeprecationWarning: 
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "

**Screenshots**
<img width="817" alt="Screen Shot 2019-05-30 at 11 28 32" src="https://user-images.githubusercontent.com/37195595/58644397-28735900-82cf-11e9-91db-807c778c06c1.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Python 3.7 running on jupyter notebook
 - pymatgen v2019.5.1

**Comment by shyuep** [comment]
For future reference, pls post such questions at http://pymatgen.discourse.group .
You can ignore the deprecation message. 

The issue is related to the fact that you are running in a Jupyter notebook. The figure is indeed generated, as can be seen from the `<Figure size ...>` in your output. For matplotlib to display the figure inline, you need to put `%matplotlib inline` first. Alternatively, run the same code as a command line script.
