### ISSUE TITLE
Composition accepts non valid formulas

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#1477]
Composition objects allow initializing with an input that is clearly not a valid formula.

For example:

```python
from pymatgen import Composition

Composition("Madeupstuff")
Composition("Lonsdalite")
Composition("MyGranddadGoesToMarketEveryTuesday")  
```

None of which raise an exception.

Is this behavior expected?

**Comment by shyuep** [comment]
This might be surprising, but yes, these are valid. Basically, pymatgen treats any non-element symbol starting with an upper-case as a DummySpecie, unless it violates the rule that the upper case letter itself is an element. For example, Composition("Stuff") would not work because S is an element. 

You can see this clearly when you look deeper at what your example gives. E.g.,

```python
In [11]: c = Composition("Madeupstuff")

In [12]: print(dict(c))
{DummySpecie Madeupstuff0+: 1.0}
```

Of course, we can be more restrictive about DummySpecie names. Just not sure how restrictive we want to be.

**Comment by utf** [comment]
I figured out that’s what was going on but I wasn’t sure if it was expected behaviour.

I was originally trying to cast to a composition check if a string was a valid formula. 

The current behaviour of composition seems fine, but it might be nice to have an ”is_valid_formula” function if that doesn’t already exist in pymatgen.

**Comment by utf** [comment]
Thanks Matt!
