### ISSUE TITLE
MagOrderingTransformation Bug with New Enumlib

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1486]
**Describe the bug**
MagOrderingTransformation seems to work with old enumlib, but fails with new enumlib. CircleCI tests are passing because those are based on the old enumlib.

**To Reproduce**
1. Compile enumlib from https://github.com/msg-byu/enumlib.git
2. Make the new enumlib default in the path.
3. Run test_advanced_transformations.
4. MagOrderingTransformation tests will fail with unable to enumerate. Given that other enumeration transformation tests passes, this is unique to the MagOrderingTransformation.

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by shyuep** [comment]
@mkhorton I suspect this has to do with the fact that MagOrdering now creates Dummy sites that collide with existing sites. But I can't be sure. In any case, I am unclear why the collision needs to occur. Shouldn't the transformation just replace existing sites with dummy sites rather than adding?

**Comment by mkhorton** [comment]
It’s because unlike enumeration of disordered structures where you enumerate species, the enumeration has to be of the spin itself (these lattices of dummy atoms containing spin). These are enumerated and then merged with the actual species after enumeration has occurred.

I can try and explain better if necessary, but basically this was necessary to get a lot of ferrimagnetic cases correct, where the spin down lattice could be from different sites of the same species or from sites from a different species.

The get_neighbors function was just a convenient way of merging the “spin lattice” with the “atom lattice.”

I am sure there are other ways to do this also, but it seemed to work quite well.

**Comment by mkhorton** [comment]
In any case, I'm also getting this. I think it's some change with how max_cell_size is handled, will investigate.

**Comment by shyuep** [comment]
@mkhorton I understand how it works broadly. What I meant is that colliding sites is not an ideal way (though the current get_all_neighbors has been fixed to deal with this). What I would suggest is that you initially do a mapping:

1. Fe2+ -> Mma: Spin.up: 0.5 and Mmb: Spin.down: 0.5
2. Replace all Fe2+ with the above (not create duplicate sites).
3. Do enumeration.
4. Reverse the mapping Mma -> Fe2+:Spin.up and MMb->Fe2+:Spin.down.

I think the site merge function is not very robust and subject to tolerances. Species mapping is trivial and will always work.

**Comment by mkhorton** [comment]
Ah yes, that sounds much more sensible.

**Comment by mkhorton** [comment]
In fact, it sounds so sensible I'm not sure why the other method was chosen...will have to re-visit.

In terms of the test failure, the enum.x output gives:

> Original d-set member was not inside the unit cell. It has been remapped.
Original:  4.528   2.614   3.453
Remapped:  0.000  -0.000  -0.000

>  d-vector didn't permute in map_dvector_permutation
 This usually means that the d-set from the input structure and the d-set
 from the struct_enum.out have a different origin or don't live in the same
 unit cell. This probably isn't your fault---the code should overcome this.

So may just be a bug in the new enum.x, will report to enumlib maintainers to see if they have ideas.

**Comment by mkhorton** [comment]
https://github.com/msg-byu/enumlib/issues/83

**Comment by shyuep** [comment]
Thanks,

**Comment by mkhorton** [comment]
FYI, Gus Hart replied -- bug known, fix promised within a few weeks, apparently significantly improved enumeration speeds also.

**Comment by shyuep** [comment]
Ok. I would suggest in the meantime that you also simplify the MagOrderingTransformation logic.

**Comment by mkhorton** [comment]
Yes, was going to take a look at that regardless

**Comment by shyuep** [comment]
Any update?

**Comment by mkhorton** [comment]
If you're asking about the enumlib bug, I'm keeping an eye on it -- myself and @ncfrey have been testing the latest enumlib version, and it seems like the bug might be fixed but only with certain compilers (it seems to work with @ncfrey via ifort, but not for myself via gfortran). But there still seems to be some weirdness going on so I'm waiting for the official release.

**Comment by shyuep** [comment]
No i mean the alternative strategy of enumerating the ordering. I find the current mag transformation way too clunky. The bug with enumlib is a separate issue.

**Comment by mkhorton** [comment]
Ah yes, ok. There was a reason for the current method which I didn’t recall during previous discussion. So you outlined the following algorithm:

1. Fe2+ -> Mma: Spin.up: 0.5 and Mmb: Spin.down: 0.5
2. Replace all Fe2+ with the above (not create duplicate sites).
3. Do enumeration.
4. Reverse the mapping Mma -> Fe2+:Spin.up and MMb->Fe2+:Spin.down.

This works well for for a single species substitution, and the mapping is easily reversible (in fact, in this case, we could just do Fe2+ -> Fe2+,spin=1/2 and Fe2+,spin=-1/2).

However, the problem comes when you want to do an ordering on multiple subsystems of different species. For example, imagine you have two magnetic species, Fe and Co, and one species compensates the other. Here the mapping combines both species (Fe and Co) under one label to do the enumeration (to ensure that net spin is zero, for example). Then we get the output from enumlib, and because both Fe and Co were given the same label, we can no longer reverse the mapping without reference to the original input structure. This is why the combining of sites takes place.

So there was a reason the current system was in place. There were some actual real, scientifically relevant case studies that motivated it, I should see if I can dig them up. Perhaps there is also a simpler implementation still though, so I can have a think about it.

**Comment by shyuep** [comment]
Perhaps I do not understand the scenario here. I understand of course you can have two magnetic species. But when can't Fe be assigned Mma and Mmb nad Co be assigned Mmc and Mmd with the appropriate occupancies for the enumeration? For instance, with say a 50-50 split for both species, you simply assign the occupancies of all of them to 0.25. Why wouldn't that give a proper net zero spin?

**Comment by mkhorton** [comment]
It would give a net zero spin, but would also introduce an additional constraint you may not want, namely in this example that there are equal amounts of up and down spin in each species: it would exclude a possible enumeration where one species has a disproportionate amount of up spin, and the other species a corresponding disproportionate amount of down spin, for a total net spin of zero. The current method doesn't see this constraint. (The physical relevance here is for those cases where one species might itself have multiple co-ordination environments, which leads to complex orderings such as this.)

**Comment by shyuep** [comment]
Isn’t this just two sequential enumeration problems? One on spin and one on species? In any case, I am curious how common this is. Most species have different spins and are not drop-in replacements. E.g., Co3+ and Fe3+ have different magmoms.

**Comment by mkhorton** [comment]
It can be; it depends on what information you know about the system beforehand. There are more targeted enumerations you can do if you have a good idea about the system, this algorithm was born as a solution to the very general case. Not so common but it happens. And yes, it's true, but we might not know the specific oxidation state ahead of time (or if it's high-spin, low-spin etc.) so the enumeration can be done purely on ordering of up/down spins irrespective of magnitude (since this defines the exchange symmetry of the system).
