### ISSUE TITLE
Inconsistent direct band gap of mp-782693 using `get_band_gap` and `get_direct_band_gap`

### ISSUE THREAD

**Issue by chc273** [materialsproject/pymatgen#1487]
**`Bandstructure.get_direct_band_gap` reports different value from `get_band_gap` for material with direct band gap**

I queried the band structure of `mp-782693` using `MPRester.get_bandstructure_by_material_id`. This material has a band gap (direct) of 0.685 eV as shown on the site and as computed by `get_band_gap` method. However, if I use `get_direct_band_gap` method on the BandStructure object, the function returns 1.555 eV. 
I have checked a few other materials with direct band gap, and such anomaly does not exist. I wonder why such things happened? Is it necessary for `BandStructure.get_direct_band_gap` to firstly check if the material has a direct band gap and if so, just return the value from `get_band_gap`? 

**To Reproduce**
```
from pymatgen import MPRester
mpr = MPRester()
bs = mpr.get_bandstructure_by_material_id('mp-782693')
print(bs.get_band_gap())
print(bs.get_direct_band_gap())
```
{'direct': True, 'energy': 0.6847, 'transition': '\\Gamma-\\Gamma'}
1.5554999999999999

**Expected behavior**
Both results should show a gap energy of 0.6847 eV.

**Desktop (please complete the following information):**

**Comment by shyamd** [comment]
This is because the two functions use different methodologies. `get_band_gap` uses the CBM and VBM points, so it doesn't care about the spin. `get_direct_band_gap` is spin-aware and it turns out in this material the CBM and VBM are from different spins, so `get_direct_band_gap` finds "another" direct band_gap where the spin doesn't change for the transition. This logic is 7 years old from when @hautierg first wrote it.

**Comment by chc273** [comment]
I see, thanks @shyamd
