### ISSUE TITLE
Remove BZT 1.0 support?

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1554]
Is there a reason to keep both bzt2 and bzt1? Or can we junk bzt1 code?

@computron

**Comment by computron** [comment]
I think there are still many people that use BZT 1.0 and not BZT 2.0

- BZT 2.0 has been harder to install for many people, especially on Mac, despite it being Python (although with C bindings, the problematic part) and BZT 1.0 being Fortran.
- BZT 1.0 allows for command-line style usage which is what a lot of scientists use and prefer. BZT 2.0 is really about working with the Python objects which is more useful but not as popular.

If look on Google Scholar for citations of Boltztrap 1.0 vs Boltztrap 2.0 since 2019 only (well into the release of Boltztrap 2.0), there are 34 *pages* of results for Bolztrap 1.0 versus 3 *pages* of of results for BZ2. i.e., 11 times more citations in 2019 to BZT 1.0.

So I think people are going to want BZT 1.0 support for awhile ...

**Comment by shyuep** [comment]
Ok...... the bzt1.0 is poorly covered by tests though.....
