### ISSUE TITLE
VoronoiNN failed for method `get_all_voronoi_polyhedra` but ok using `get_voronoi_polyhedra` on all site indices.

### ISSUE THREAD

**Issue by chc273** [materialsproject/pymatgen#1591]
**pymatgen.analysis.local_env.VoronoiNN potential bug**

I tried to compute the Voronoi Tessellation of surface structures. Using `get_all_voronoi_polyhedra` it reports `pathological structure` error. However, there is no error if I run `get_voronoi_polyhedra` on each site index. I wonder if this is a bug? 

**To Reproduce**
```
from pymatgen.analysis.local_env import VoronoiNN
from pymatgen import Structure

s = Structure.from_str("""V12
1.0
2.459662 0.000000 0.000000
0.000000 4.471437 0.000000
0.000000 0.000000 29.515945
V
12
direct
0.000000 0.000000 0.916206 V
0.000000 0.000000 0.994721 V
0.500000 0.500000 0.959167 V
0.500000 0.500000 0.874547 V
0.000000 0.000000 0.749499 V
0.000000 0.000000 0.833633 V
0.500000 0.500000 0.792168 V
0.500000 0.500000 0.708033 V
0.000000 0.000000 0.582499 V
0.000000 0.000000 0.667120 V
0.500000 0.500000 0.625461 V
0.500000 0.500000 0.546946 V
""", fmt='POSCAR')

vnn = VoronoiNN()

try:
    all_polys = vnn.get_all_voronoi_polyhedra(s)
except Exception as e:
    print('get_all_voronoi_polyhedra error: ')
    print(e)

try:
    for i in range(len(s)):
        poly = vnn.get_voronoi_polyhedra(s, i)
except Exception as e:
    print('get_voronoi_polyhedra failed with index %d' %i)
    print(e)
```

**Comment by mkhorton** [comment]
Hi Chi -- I didn't write this class, but this behavior is not completely unexpected with Voronoi.

When asking to get the Voronoi polyhedra for a single site, only the sites immediately surrounding that site are given to the Voronoi tessellation algorithm, whereas when all sites are requested, all sites in the structure are given. Therefore it is entirely possible that asking for each site individually might work, but all sites together will not. Some combinations of co-ordinates can cause the Voronoi algorithm to fail, e.g. see this previous bug report https://github.com/scipy/scipy/issues/8929

I imagine this might be fixed with a different choice of cut-off radius but I have not investigated. You may want to try changing the `cutoff` kwarg and the `allow_pathological` kwarg in the `VoronoiNN` constructor. Please report back if you manage to fix this!

**Comment by chc273** [comment]
Thanks @mkhorton. I understand that with all the points included in the voronoi tessellation, it is more prone to error. My expectation is only that the get all voronoi polyhedron should return a list the same way as I compute each site individually (its a reasonable expectation right?). The problem is more related to implementation than physics. I will test options and let you know. Thank you again.

Chi

**Comment by mkhorton** [comment]
Yes agreed, it’s a completely reasonable expectation. I don’t know if there
are more robust Voronoi implementations out there, or if it’s a fundamental
limitation.

**Comment by chc273** [comment]
@mkhorton For the above example, it seems that increasing Voronoi cutoff to 20 Angstrom "cured" the pathological structure. Strange enough. I will close this issue. Thank you for the suggestion!
