### ISSUE TITLE
CIFs with symmetrical molecules generated from CSD.

### ISSUE THREAD

**Issue by SarahEW** [materialsproject/pymatgen#1687]
I am using pymatgen to generate VASP input files such as POSCAR from cif files generated from the CSD python API. This mostly works well, but if a molecule is symmetrical atoms can sometimes be labeled as such C1 C1A etc. which pymatgen does not deal with so well.

s = Structure.from_file("MCHTEP11.cif")

C:\ANACONDA3\envs\python3-env\lib\site-packages\pymatgen\io\cif.py:1001: UserWar
ning: Some occupancies ([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) sum to > 1! If
they are within the tolerance, they will be rescaled.
  warnings.warn(msg)
C:\ANACONDA3\envs\python3-env\lib\site-packages\pymatgen\io\cif.py:1105: UserWar
ning: Species occupancies sum to more than 1!
  warnings.warn(str(exc))
C:\ANACONDA3\envs\python3-env\lib\site-packages\pymatgen\io\cif.py:1107: UserWar
ning: Issues encountered while parsing CIF:
  warnings.warn("Issues encountered while parsing CIF:")
C:\ANACONDA3\envs\python3-env\lib\site-packages\pymatgen\io\cif.py:1109: UserWar
ning: Some occupancies ([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) sum to > 1! If
they are within the tolerance, they will be rescaled.
  warnings.warn(error)
C:\ANACONDA3\envs\python3-env\lib\site-packages\pymatgen\io\cif.py:1109: UserWar
ning: Species occupancies sum to more than 1!

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7

**Comment by shyuep** [comment]
This is not a bug but rather because the code detects that some of the atoms are effectively in the same place. Having more than one atom in a physical location makes no sense. But we are aware that some CIF files violate this.

You can resolve this by setting merge_tol to some large positive value or you can directly use the pymatgen.io.cif.CifParser class which has more fine-grained control.

**Comment by OphirKa** [comment]
Hello,
I have the same issue and tried to treat it in both ways (even set merge_tol from 0.01 to 1.0) and the problem is still exist. 
Is there any other option? Change anything in the file?
One of the problematic cif files is attached. 
[hmx.txt](https://github.com/materialsproject/pymatgen/files/9371949/hmx.txt)
