### ISSUE TITLE
W_pv not included in newer POTCAR versions

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#1707]
**Describe the bug**
W_pv POTCAR does not exist in the newer POTCAR versions (PBE_54). Using the MVLScanRelaxSet or the LobsterSet for compounds including W will therefore result in an error:

**To Reproduce**
`from pymatgen.ext.matproj import MPRester`
`from pymatgen.io.vasp.sets import MVLScanRelaxSet`
`a = MPRester()`
`struct = a.get_structure_by_material_id('mp-1191364')`
`set = MVLScanRelaxSet(structure=struct, potcar_functional="PBE_54")`
`set.write_input(output_dir=".")`

Does anyone have a suggestion how to fix this? Since a change would affect standard configurations, I wanted to ask for help.

Best, 
JG

**Comment by shyuep** [comment]
I would suggest we simply use have a different YAML setting file that specifies W instead of W_pv as the PSP.

**Comment by mkhorton** [comment]
We noticed this ourselves recently -- the immediate fix is simply to add `user_potcar_functions={"W":"W_sv"}` I believe. The _sv seems like the better pseudo potential anyway.

More broadly, we're working to rigorously benchmark and improve on MVLScanSet (@rkingsbury) and this will likely see a new base set with different potcar choices. @rkingsbury has recently been adding potcar hash checking to the input sets also, so that we can have more robust checking against using incorrect potcars.

**Comment by JaGeo** [comment]
Thank you very much for the ideas. I will try to find a solution for the LobsterSet. It should however still allow to use the old PBE POTCARs. Lobster will work with them as well. I might need to change the config depending on which POTCAR version is chosen.
