### ISSUE TITLE
Add optional n parameters to all "Get neighbours" functions in structure

### ISSUE THREAD

**Issue by mm04926412** [materialsproject/pymatgen#1737]
Hello

As it stands there are many methods to get all sites within a radius r of some co-ordinates / site in a crystal. I notice that there is no way to specify 'n' instead where r is chosen to give exactly n sites. this functionality seems intuitive and I imagine fairly easy to add would it be possible to include this in an update?

Thanks

Mike

**Comment by shyuep** [comment]
While this is possible, but it would be highly inefficient since it is not possible to a priori know what r should be to get n neigbors. The easier way is simply to use `nn = get_all_neighbors(..)` with a reasonable r (say 5A), and then just take the first n neighbors. E.g., `nn[:n]`.

**Comment by mkhorton** [comment]
@shyuep we could add that functionality as a convenience method (e.g. pick r, trim the list)? I can see why people might find it useful. However, *exactly* n sites would be impossible to guarantee. N neighbor shells might be more generally useful.

**Comment by shyuep** [comment]
@mkhorton I am in general not supportive of convenience methods that implement a one-liner in python (it is literally just nn[:n] as I wrote, since the nn returned is in increasingly order of distance), unless it is supremely unintuitive for people to figure out and is used by > 80% of people. 

As for N neighbor shells, that is potentially useful but non-trivial to implement. You'd have to use some form of clustering (similar to what was used in determining surface sites) because atoms that are r and r+-0.001 A should be considered in the same shell due to numerical considerations. That delta tolerance is non-trivial. Scipy cluster can do it of course. Not clear how many people would use it.

**Comment by mkhorton** [comment]
We might be able to add on N neighbor shells to the NearNeighbor class, i.e. define shells by number of bonds, rather than geometric distance. For use cases, I've see this for extracting clusters from a larger supercell e.g. for multiscale QM/MM simulations etc. 

Fair point on the convenience method, let's leave that alone then.
