### ISSUE TITLE
Numerical error produces lattice with values close to 0, but negative

### ISSUE THREAD

**Issue by felentovic** [materialsproject/pymatgen#1745]
**Describe the bug**
In the class `Lattice` the method `from parameters` in some cases creates lattice vectors which have a value close to zero, but negative. E.g  [5.61018515, 0.0, 3.435247643285757e-16]. This accumulates errors later in calculations.

**To Reproduce**
Create a lattice from parameters with the following arguments:
a = {float64} 5.61018515
b = {float64} 5.61018515
c = {float64} 20.95050049
alpha = {float64} 90.0
beta = {float64} 90.0
gamma = {float64} 90.0

The result is:
Lattice vectors: [a,b,c]
<class 'list'>: [[5.61018515, 0.0, 3.435247643285757e-16], [-3.435247643285757e-16, 5.61018515, 3.435247643285757e-16], [0.0, 0.0, 20.95050049]]

**Expected behaviour**
Lattice vectors: [a,b,c]
<class 'list'>: [[5.61018515, 0.0, 0.0], [0.0, 5.61018515, 0.0], [0.0, 0.0, 20.95050049]]

**Desktop:**
 - OS: Mac,Linux
 - Version:  2020.1.10

**Comment by mkhorton** [comment]
Thanks for the report @felentovic, Negative values are not intrinsically incorrect and somewhat inevitable given the nature of floating point arithmetic -- can you give a specific example of error accumulation leading to a bug?

This said, I agree it's unfortunate there are these small-non-zero values in this very simple case. It's possible to initialize directly from the matrix, since this is the internal representation of the lattice, to avoid this issue. I'll take a look at the math we're using also in case there's a cleaner solution here.

**Comment by shyuep** [comment]
This isn’t a bug but rather a reality of floating point arithmetic. I have yet to encounter a real world situation that this matters. Closing this.
