### ISSUE TITLE
Improve error messages in MPRester for unknown materials or missing material properties

### ISSUE THREAD

**Issue by paulneves77** [materialsproject/pymatgen#1756]
**Description:**
I get an error when calling **get_bandstructure_by_material_id** on material **mp-769885**. I do not know if this error is also present in other materials, nor whether the error is due to the get_bandstructure_by_material_id function or in the material itself. I have been able to use get_bandstructure_by_material_id with over 30 other materials without issue.

**To Reproduce:**
```
with MPRester(<API_KEY>) as m:
    bs = m.get_bandstructure_by_material_id('mp-769885')
```

**Error Message:**
```
    File "<FOO.PY>", line 71, in <module>
        bs = m.get_bandstructure_by_material_id('mp-769885')

    File "C:\Users\<USERNAME>\Anaconda3\lib\site-packages\pymatgen\ext\matproj.py", line 625, in get_bandstructure_by_material_id
        return data[0][prop]

IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Current as of Feb 2, 2020

Any guidance would be much appreciated!

**Comment by mkhorton** [comment]
Hi @paulneves77,

Not all materials have band structures associated with them. If you visit this [materials details page](https://materialsproject.org/materials/mp-756234) you can see there is no band structure supplied, which is why you have the error. The error message could be more useful however! Later in the year, we're planning a big data release with a lot of new band structures available.

It looks like for this material, we have calculated a band structure (see [here](https://materialsproject.org/tasks/mp-756234#mp-844812)), but for whatever reason it's not currently available on the website or via the API -- maybe @shyamd can comment?

Since this is a Materials Project data question, a more appropriate place to ask would be on the [Materials Project discussion forum](https://discuss.matsci.org/c/materials-project/).

I'll leave this issue open here however to make a note that we should improve the error messages for materials where band structures are not available.

**Comment by paulneves77** [comment]
Thanks for the information @mkhorton!

I thought I saw a band structure calculation for this material on the materials project, but I must have been mistaken.

I am still confused about one point though: I was able to run **get_bandstructure_by_material_id** on many materials that do not have a band structure calculated in the materials project (to pick a random example, [mp-767194](https://materialsproject.org/materials/mp-767194/)), and it does not error and end the program. Instead, get_bandstructure_by_material_id just returns None. I am unclear on the difference between querying mp-767194 and mp-769885: why does one error while the other does not? Perhaps it is that there is a band structure calculated for mp-769885, as you mentioned.

At any rate, returning None instead of giving an Error if there is no available band-structure makes more sense in my mind. I am running a search based on a list of selected material IDs, looking at all the available band structures (that data release of new band structures sounds exciting!). If it crashes when it gets to materials like mp-769885, the program will never complete!

Also, in the spirit of unclear error messages, I am getting a different error when I try to use get_bandstructure_by_material_id on [mp-756234](https://materialsproject.org/materials/mp-756234/), which does have a calculated bandstructure. It says:

```
In [51]: m.get_bandstructure_by_material_id('mp-767633')
Traceback (most recent call last):

  File "<ipython-input-51-363b57d22dbb>", line 1, in <module>
    m.get_bandstructure_by_material_id('mp-767633')

  File "C:\Users\pmneves\Anaconda3\lib\site-packages\pymatgen\ext\matproj.py", line 624, in get_bandstructure_by_material_id
    data = self.get_data(material_id, prop=prop)

  File "C:\Users\pmneves\Anaconda3\lib\site-packages\pymatgen\ext\matproj.py", line 241, in get_data
    return self._make_request(sub_url)

  File "C:\Users\pmneves\Anaconda3\lib\site-packages\pymatgen\ext\matproj.py", line 188, in _make_request
    raise MPRestError(msg)

MPRestError: REST query returned with error status code 504. Content: b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"
```

Do you think I should open a thread on the MP forum about these concerns?

**Comment by mkhorton** [comment]
> Do you think I should open a thread on the MP forum about these concerns?

In general, yes, but since this thread is already open don't worry about it -- a similar group of people read both places, it's mostly an organizational thing to help us keep track.

> If it crashes when it gets to materials like mp-769885, the program will never complete!

A remedy here, for now, is to wrap it in a try/except:

```
try:
    with MPRester(<API_KEY>) as m:
        bs = m.get_bandstructure_by_material_id('mp-769885')
except MPRestError:  # you may need to `import MPRestError` from the relevant module
    pass
```

In this way, you could also keep a list of mp-ids for which band structures are not available.

Regarding the issue itself, I'll raise this at our weekly meeting to discuss.
