### ISSUE TITLE
Extracting the asymmetric single molecule from the CIF file

### ISSUE THREAD

**Issue by misterblonde** [materialsproject/pymatgen#1774]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I try to use Pymatgen to extract the single molecule in the asymmetric unit of a .cif file. I hope that _unique_coords() inside cif.py would offer this functionality, but I don't seem to get this to work? I only have sites but it requires actual coords as input. the entire function is not documented anywhere. 

**Describe the solution you'd like**
can you please show me a sample implementation of this function? If this is not the right function to do what I'm trying to do, please suggest the correct function to use. 

**Describe alternatives you've considered**
I also tried the simple .cif to .xyz io/conversion, however that just gives you all the atoms inside the unit cell in cartesian coordinates, which is not very useful for my purposes. 

**Additional context**
this functionality was offered by an old version of open babel, but then got deprecated, because it's not a trivial problem. I really look forward to your reply. THANK YOU.

**Comment by mkhorton** [comment]
Hi @misterblonde, can you be more specific about what you mean by "extract the single molecule in the asymmetric unit of a .cif file"?

>  the entire function is not documented anywhere.

Functions with leading underscores in Python are considered "private" so may not contain docstrings. They're there for ease of maintenance, rather than to be called by the end user.

It's a little convoluted, but there is one method to extract molecules from an arbitrary CIF file, see https://pymatgen.org/pymatgen.analysis.graphs.html#pymatgen.analysis.graphs.StructureGraph.get_subgraphs_as_molecules -- this requires prior bond detection using one of the bonding algorithms in pymatgen.analysis.local_env, and then it uses the bonding information to extract individual molecules (even if they straddle periodic boundaries). This functionality has not been used extensively, so issue reports would be welcome.

**Comment by misterblonde** [comment]
Hi @mkhorton! 

Thanks for your quick response!  The asymmetric molecule is the molecule in the unit cell, which all the symmetry operations are based upon. So basically the molecule that you get without any translations/rotations. Then you can use that molecule to build the supercell by translating/rotating it. 
I know you currently employ the opposite approach of just periodically replicating the unit cell to build the supercell. I would look for something that just returns me the single molecule, assuming a Z'=1 crystal structure, ie. only one molecule in the asymmetric unit. 

I had a look at the graphs module, but I guess you don't have any examples on how to use it yet? Would you just use nx to convert into the right graph format? Does Pymatgen not offer a way to  convert from my _Pymatgen parsed cif_ to the _MSONable graph_ format?  

`from pymatgen.io.cif import CifParser

parser = CifParser(filn)
struc = parser.get_structures()[0]`

Sorry, I tried to get into your code before because I thought it would be super useful, but none of the sample notebooks, answered the questions I had 😃 Maybe there's a new resource/sample page now?

**Comment by mkhorton** [comment]
> I had a look at the graphs module, but I guess you don't have any examples on how to use it yet? Would you just use nx to convert into the right graph format? Does Pymatgen not offer a way to convert from my Pymatgen parsed cif to the MSONable graph format?

I don't have an example to hand, but usage is basically:

```
from pymatgen.analysis.graphs import StructureGraph
from pymatgen.analysis.local_env import MinimumDistanceNN

nn = MinimumDistanceNN()
sg = StructureGraph.with_local_env_strategy(my_struct, nn)
molecules = sg.get_subgraphs_as_molecules()
```

but this is a very inefficient way to do it for the "asymmetric molecule" you described, since this data is already in the CIF...

We should definitely have an example notebook :)

**Comment by misterblonde** [comment]
Hey thank you! The code you sent works and I get a single molecule in xyz coordinates. However, when I compare the single molecule extracted to the xyz supercell generated using the `.make_supercell `function, then the single molecule is not periodically related to the supercell. I opened both in pymol to see (photos attached). Ideally, I would want to be able to extract all the possible nearest neighbour dimer pairs of the two molecules in the central unit cell/center of the supercell. Could I "repair the broken fragments" of the supercell somehow, or set periodic boundary conditions to false (pbc=false)? I also tried to see if the graph module offers any functionality to find all the molecules and delete broken ones instead? No luck. 
<img width="463" alt="supercell_on_its_own" src="https://user-images.githubusercontent.com/35377468/75617169-84526300-5b29-11ea-8d7d-0c4bc8d8b1bf.png">
<img width="485" alt="supercell_with_misplaced_single_mol" src="https://user-images.githubusercontent.com/35377468/75617170-84526300-5b29-11ea-8b1b-9830bac0b379.png">

**Comment by bokertof** [comment]
> > I had a look at the graphs module, but I guess you don't have any examples on how to use it yet? Would you just use nx to convert into the right graph format? Does Pymatgen not offer a way to convert from my Pymatgen parsed cif to the MSONable graph format?
> 
> I don't have an example to hand, but usage is basically:
> 
> ```
> from pymatgen.analysis.graphs import StructureGraph
> from pymatgen.analysis.local_env import MinimumDistanceNN
> 
> nn = MinimumDistanceNN()
> sg = StructureGraph.with_local_env_strategy(my_struct, nn)
> molecules = sg.get_subgraphs_as_molecules()
> ```
> 
> but this is a very inefficient way to do it for the "asymmetric molecule" you described, since this data is already in the CIF...
> 
> We should definitely have an example notebook :)

Hello! I faced the same problem. I've not seen any functions to get assymetric unit from CIF-file. By default string `parser.get_structures()[0]` gets all atoms within unit cell however for my purposes I need only assymetric part (i.e. only atoms which are listed inside CIF-file). I tried your example with subgraph search but it's really inefficient approach. Maybe is there more simple way to extract assymetric unit? Because as I can see it'd not be a big problem.
