### ISSUE TITLE
StructureGraph produced a multi-directed graph

### ISSUE THREAD

**Issue by tawe141** [materialsproject/pymatgen#1811]
**Describe the bug**
Not sure if this is a bug or something that's undocumented, but `StructureGraph.with_local_env_strategy(struct, CrystalNN())` produces a MultiDiGraph. This doesn't make much sense to me, since bonds do not inherently have directionality. This also inhibits intuitive use of the underlying `networkx` object. 

**To Reproduce**

Using [this cif file](https://www.dropbox.com/s/p6pv1o98x7zwvoh/pn_Mg.cif?dl=0), run the following:
```
struct = CifParser('pn_Mg.cif').get_structures(primitive=False)[0]
g = StructureGraph.with_local_env_strategy(struct, CrystalNN(distance_cutoffs=None, x_diff_weight=0.0))
type(g.graph)

# last line returns "networkx.classes.multidigraph.MultiDiGraph"
```

**Expected behavior**
I would expect a Graph or MultiGraph object. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: 2020.3.13

**Comment by mkhorton** [comment]
This is not a bug. We have to define bonds for _periodic_ solids and this means each bond does not just have a `from_atom` and a `to_atom` but also a `to_image` which encodes which periodic image the bond is pointing towards.

Consider an example of a simple cubic structure with a single atom whose single atom is bonded to itself -- this now has 6 bonds, the `from_atom` and `to_atom` are identical for all 6 bonds, only the `to_image` changes.

Since the nodes define the `from_atom` and `to_atom` the edges are between the same two nodes for all 6 bonds, the difference is in the edges which are encoded with the `to_image` metadata.

Therefore a MultiDiGraph is required if defining graphs in this manner.

**Comment by mkhorton** [comment]
And just to clarify why it's a directional graph: the directionality is required so that you know which node corresponds to the `to_image` is referring to.

There are of course other ways to represent periodic solids as graphs, they variously have different advantages and disadvantages. The situation for molecules is much simpler and a normal `Graph` is fine.
