### ISSUE TITLE
Connection problem with MPRester

### ISSUE THREAD

**Issue by liuyuhang599** [materialsproject/pymatgen#1821]
I got this error message while downloading data from the Materials Project using MPRester.

MPRestError: ('Connection aborted.', OSError("(10051, 'WSAENETUNREACH')"))

**Comment by shyuep** [comment]
The likelihood is that the Materials PRoject is down. You will need to contact the Materials Project people.

**Comment by mkhorton** [comment]
Yes, an error like that is usually a connection issue, not a pymatgen issue.

We haven't registered any connection issues with Materials Project since March 6th (35 minutes), though I would not be surprised if we might likely have some issues in the future due to the shelter-in-place. So far, we have mostly been able to work as normal however.

I notice this is a Windows error, if it persists, perhaps try seeing if the `requests` library is working at all in your installation and/or try an alternative installation (Google Colab is a great resource to try pymatgen, you can `!pip install pymatgen` in the cloud using any Google account).
