### ISSUE TITLE
module 'pymatgen' has no attribute 'DeformedStructureSet'

### ISSUE THREAD

**Issue by glwhart** [materialsproject/pymatgen#1853]
Not sure if this is a bug or just newbie user error---my first time trying to use pymatgen

When I call the `DeformedStructureSet` function, I get the message shown in the title

```
hcp = mg.Lattice.hexagonal(3.23,5.14)
str = mg.Structure(hcp,["Zr","Zr"],[[0,0,0],[1/3,1/3,1/2]])
dfm = mg.DeformedStructureSet(str,[0.1])
```

**Comment by mkhorton** [comment]
Hi Gus, welcome :-)

`DerformedStructureSet` lives in `pymatgen.analysis.elasticity.strain' [here](https://pymatgen.org/pymatgen.analysis.elasticity.strain.html#pymatgen.analysis.elasticity.strain.DeformedStructureSet).

Rather than needing to include a long method call, it's usually easier to import explicitly at the top of your script, so you could write as follows:

```
import pymatgen as mg
from pymatgen.analysis.elasticity.strain import DeformedStructureSet

hcp = mg.Lattice.hexagonal(3.23, 5.14)
struct = mg.Structure(hcp, ["Zr", "Zr"], [[0, 0, 0], [1/3, 1/3, 1/2]])
dfm = DeformedStructureSet(struct, [0.1])
```

And then you access the deformed structures using `def.deformed_structures`.

Finally, just a note to be careful with naming -- if you call your structure `str`, you're going to over-write the Python built-in "string" type.

**Comment by glwhart** [comment]
Matthew, thank you for the quick and helpful response. I suspected it was something simple.
