### ISSUE TITLE
symmetry_reduce: AttributeError: 'Structure' object has no attribute 'transform'

### ISSUE THREAD

**Issue by glwhart** [materialsproject/pymatgen#1855]
This is probably my misuse of pymatgen or my weak python skills but...

I created an hcp structure:
```
>>> hcpZr
Structure Summary
Lattice
    abc : 3.23 3.2300000000000004 5.14
 angles : 90.0 90.0 119.99999999999999
 volume : 46.440704076633324
      A : 3.23 0.0 1.9778045806229754e-16
      B : -1.6149999999999993 2.7972620542237374 1.9778045806229754e-16
      C : 0.0 0.0 5.14
PeriodicSite: Zr (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: Zr (0.5383, 0.9324, 2.5700) [0.3333, 0.3333, 0.5000]
```
then generated 24 distortions using `DeformedStructureSet`. Then I tried to reduce them using `symmetry_reduce`. The deformed set of structures are in the list `dfm`. I get the following error:
```
>>> uqdfm = symmetry_reduce(dfm,hcpZr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hart/.virtualenvs/p3/lib/python3.7/site-packages/pymatgen/core/tensors.py", line 1039, in symmetry_reduce
    if np.allclose(unique_tensor.transform(symmop), tensor, atol=tol):
AttributeError: 'Structure' object has no attribute 'transform'
```

Is there a forum where I should be asking for this kind of help? I'm not sure I should be raising github issues for these kinds of questions...

Thanks so much.

**Comment by shyuep** [comment]
The symmetry_reduce method is meant to operate on symmetry operations rather than a list of structures.

For the purposes of this method, you can simply initialize the DeformedStructureSet with the kwarg symmtry=True. E.g.,

```
dfm = DeformedStructureSet(structure, symmetry=True)
```

This will perform symmetry reduction.
We have a Discourse forum at https://matsci.org/c/pymatgen which is meant for answering all help questions regarding pymatgen. In general, matsci.org is a collection of forums for various software packages used by materials scientists.

**Comment by glwhart** [comment]
Thanks Shyue. Quite helpful.

**Comment by mkhorton** [comment]
Just a quick note, we've added redirects for each project to make the url easier to remember, so you can use just https://matsci.org/pymatgen

**Comment by mkhorton** [comment]
We're also welcoming other projects to host their discussions on that website for their own codes, an open offer !
