### ISSUE TITLE
Fail to read CIF file from the CSD database

### ISSUE THREAD

**Issue by danieleongari** [materialsproject/pymatgen#1867]
When running
```
from pymatgen.io.cif import CifParser
parser = CifParser("FIQCEN.cif")
structure = parser.get_structures()[0]
```
with FIQCEN being a structure from the CSD database (https://www.ccdc.cam.ac.uk/solutions/csd-system/components/csd/), the script returns the error:
```
/home/daniele/anaconda3/envs/csd/lib/python3.7/site-packages/pymatgen/io/cif.py:1106: UserWarning: Issues encountered while parsing CIF:
  warnings.warn("Issues encountered while parsing CIF:")
/home/daniele/anaconda3/envs/csd/lib/python3.7/site-packages/pymatgen/io/cif.py:1108: UserWarning: Some occupancies ([10, 19, 6, 6, 6, 6]) sum to > 1! If they are within the tolerance, they will be rescaled.
  warnings.warn(error)
/home/daniele/anaconda3/envs/csd/lib/python3.7/site-packages/pymatgen/io/cif.py:1108: UserWarning: Species occupancies sum to more than 1!
```
Note that the file is correctly visualized by software such as VESTA:
![image](https://user-images.githubusercontent.com/25899092/84133031-e7b43100-aa46-11ea-9495-dd315de6c371.png)

[FIQCEN.cif.log](https://github.com/materialsproject/pymatgen/files/4751327/FIQCEN.cif.log)

I tried also 
```
parser = CifParser("FIQCEN.cif", occupancy_tolerance=100)
```
which results in `core dumped`.

Thanks for your support!

Environment:
 - OS: Linux
 - Version: 2020.6.8

**Comment by danieleongari** [comment]
After further testing, using the previous version `pymatgen-2020.4.29`, the script as:
```
parser = CifParser("FIQCEN.cif", occupancy_tolerance=100)
```
works fine.
Please check if the is a bug in the latest version and document the need of `occupancy_tolerance=somehighnumber` in https://pymatgen.org/usage.html

**Comment by mkhorton** [comment]
Hi @danieleongari ,

These are not errors, they are warnings:

```
UserWarning: Issues encountered while parsing CIF:
UserWarning: Some occupancies ([10, 19, 6, 6, 6, 6]) sum to > 1! If they are within the tolerance, they will be rescaled.
UserWarning: Species occupancies sum to more than 1!
```

(removed the file paths so it can be read more easily)

The warning is to tell you that some aspects of your CIF are unusual: it's claiming that there are more than one atom on a given site, so some manual attention is suggested to make sure this is what you intend.

> which results in core dumped.

This is typically an installation issue, it could be that your `spglib` needs to be updated? I'll test also to see if 2020.6.8 has a specific issue, thanks for reporting.

**Comment by mkhorton** [comment]
Hi @danieleongari , just to update on this we did find an issue with the Linux wheels for 2020.6.8 so a re-install might help.

**Comment by danieleongari** [comment]
Thanks @mkhorton for letting me know.
Aside from the "core dumped" problem,
I would still suggest to make the error more verbose and suggesting how to fix the warning, because the definition of "occupancy_tolerance" is not a trivial concept and might confuse the user: I had to spend some time diving into the code to catch it!

Something like:
```
UserWarning: Species occupancies sum to more than 1! Increase occupancy_tolerance to get the structure.
```

**Comment by mkhorton** [comment]
That's a good suggestion, thanks! Will make a change to improve the phrasing.

For some context (or for anyone else reading this for which it might be useful), occupancies on an individual site should ideally sum to 1.0. What this means is that if the site is disordered (it can contain more than one element on average) then statistically we know what elements are present, and what the probability is that the site contains a given element.

A sum > 1.0 doesn't make physical sense because then the probabilities are no longer well defined. However, in some large databases, this does happen sometimes -- often because occupation probabilities for individual elements are measured independently and so the small amount of error means they round to just about 1.0 and that's where "occupancy_tolerance" is most useful. The other scenario is that some databases don't follow the CIF specification appropriately, which means they're using occupancies that sum up to 100 instead of 1. Technically, this is an error, but if you know to look for it you can just scale occupancies down by a factor of 100 to get the correct result.
