### ISSUE TITLE
Jupyter notebook bug.

### ISSUE THREAD

**Issue by keduemml** [materialsproject/pymatgen#1889]
I am going through the Jupiter notebook tutorials and am trying to reproduce the 2013-01-01-Bandstructure of NiO tutorial. The issue I am running into is with the run = BSVasp("vasprun.xml", parse_projected_eigen=True) command. The error is ParseError: no element found: line 486, column 0.
That is the last line in the vasprun.xml file and when I try the same line of code for a different vasprun.xml file it always has the same error on the last line in the vasprun.xml file.
I am running pymatgen 2020.4.2 on windows.

**Comment by mkhorton** [comment]
Which vasprun.xml are you using?

**Comment by keduemml** [comment]
The vasprun.xml file that is generated from running VASP. Im not sure how else to explain it, are there different vasprun.xml files.

**Comment by mkhorton** [comment]
The reason I ask is that usually this kind of error is the result of a mal-formed vasprun.xml file, e.g. one in which VASP didn't complete writing the full file. You could try again with one of the example vasprun.xml files in our [test_files folder](https://github.com/materialsproject/pymatgen/tree/master/test_files), to diagnose whether the issue is with the specific file you're using or not.

If this isn't a bug, a good place to ask questions is in our user forum at matsci.org/pymatgen.

**Comment by keduemml** [comment]
I will check with the forum page, I was unaware that there was one. I have compared my vasprun.xml file to the one in the folder you linked and there are significant differences mine ends much earlier and explains why I was getting the error I was. Which mean this isn't a bug in pymatgen.
Thank you for your help mkhorton.

**Comment by mkhorton** [comment]
No problem, glad it was helpful. And yes, we should advertise the forum more loudly on our documentation page, I'll have to make that change.
