### ISSUE TITLE
Labelling for COHP bonds

### ISSUE THREAD

**Issue by CifLord** [materialsproject/pymatgen#1909]
Is there any reason for how an individual bond's COHP gets its label in the CompleteCOHP class (pymatgen.electronic_structure.cohp.py)? It seems to me that the labels are just distinct integers arbitrarily assigned to each bond. If that is the case, I suggest that we might switch to a labeling system where the label is a tuple of the two site indices that make up a COHP bond. This would make searching for a specific COHP via the get_cohp_by_label() method much easier.

**Comment by JaGeo** [comment]
Hi!
The label corresponds to the label from the ICOHPLIST. We could discuss alternatives but I preferred this as there can be multiple COHPs for a site combination.

**Comment by richardtran415** [comment]
Ah OK then, thank you clearing this up. I agree its a hassle to have to think about what site we're dealing with to get a specific COHP. I'll try to think up alternate scheme to organize this since as you said there can be more than one COHP for a pair.

**Comment by JaGeo** [comment]
Just to add: I think still think using the labels from the ICOHPLIST makes it very user-friendly (I would also prefer to keep it this way because you can easily identify relevant bonds by checking the ICOHPLIST) but we might be able to add additional ways to identify the relevant COHPs. I agree that there might be potential for improvement.
