### ISSUE TITLE
Running SpacegroupAnalyzer on enumerated structure returns wrong space group

### ISSUE THREAD

**Issue by DoubleKx** [materialsproject/pymatgen#1913]
I'm trying to take my enumerated primitive cell and return it back to the conventional cell but it's not finding the original space group.

Steps I took:
1. Input conventional cell (s.g. F-43m) and find the primitive cell using SpacegroupAnalyzer.find_primitive()
2. Enumerated using enumlib (i.e. EnumerateStructureTransformation) OR OrderDisorderedStructureTransformation()
3. Generate POSCAR files of enumerated structures
3. Run enumerated cells through SpacegroupAnalyzer.get_refined_structure() and get_space_group_symbol()
4. Result is always P1 or the incorrect space group. It does not find F-43m for some reason even after adjusting tolerances in SpacegroupAnalyzer

[Input_Files.zip](https://github.com/materialsproject/pymatgen/files/4944706/Input_Files.zip)

See the attached CIF file for the conventional cell and the POSCAR after enumeration in step 3

**Comment by mkhorton** [comment]
The enumerated structure (ordered approximation) will necessarily be lower symmetry than the input disordered structure, so it's reasonable that it would no longer read as F-43m.

**Comment by DoubleKx** [comment]
Ah, I see. So what about after relaxing the structure with DFT? Is there a function or way to "rebuild" the relaxed enumerated primitive structure to the conventional cell in F-43m?

**Comment by mkhorton** [comment]
You can substitute back disordered species for your ordered species (e.g. if you started with {A: 0.5, B: 0.5} on a site, created an ordered approximation, after relaxation you could replace A with {A: 0.5, B: 0.5} and B with {A: 0.5, B: 0.5}). You could then do a structure refinement with a loose symmetry tolerance. This is obviously more difficult if A or B is a vacancy rather than another species. In general though, "going back" is difficult, precisely because you're lowering the symmetry and there'll be local relaxations around your various species, bond lengths will be changing, etc. so it's not a trivial thing. 

What you might find useful is storing the mapping (eg lattice transformation) between primitive and conventional cells and then re-applying that mapping after your DFT relaxation.

**Comment by DoubleKx** [comment]
Thanks! That was very useful. I did this using find_mapping in the lattice module and applied the mapping

**Comment by mkhorton** [comment]
Great! Glad it helped.
