### ISSUE TITLE
Error in fetching band structure for specific materials id

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#1941]
The following script/URL, either 

mpr.get_bandstructure_by_material_id("mp-867624") 

or

https://www.materialsproject.org/rest/v2/materials/mp-867624/vasp/bandstructure?API_KEY=************

gives the error: 

{
  "valid_response": false,
  "error": "too many indices for array: array is 0-dimensional, but 2 were indexed",
  "version": {
    "db": "2020.08.21",
    "pymatgen": "2020.8.3",
    "rest": "2.0"
  },
  "created_at": "2020-08-26T11:00:09.393429",
  "traceback": "Traceback (most recent call last):\n  File \"/var/www/python/matgen_prod/materials_django/rest/rest.py\", line 94, in wrapped\n    d = func(*args, **kwargs)\n  File \"/var/www/python/matgen_prod/materials_django/materials/rest.py\", line 114, in get_vasp_property\n    loadee=d[\"response\"])\n  File \"/var/www/python/matgen_prod/materials_django/materials/rest.py\", line 56, in mid_ETL\n    value = transform(s)\n  File \"/var/www/python/matgen_prod/materials_django/materials/rest.py\", line 68, in es_transform\n    return extracted.as_dict()\n  File \"/opt/miniconda3/envs/mpprod3/lib/python3.6/site-packages/pymatgen/electronic_structure/bandstructure.py\", line 858, in as_dict\n    d[\"is_metal\"] = self.is_metal()\n  File \"/opt/miniconda3/envs/mpprod3/lib/python3.6/site-packages/pymatgen/electronic_structure/bandstructure.py\", line 307, in is_metal\n    if np.any(values[i, :] - self.efermi < -efermi_tol) and \\\nIndexError: too many indices for array: array is 0-dimensional, but 2 were indexed\n"
}

**Comment by mkhorton** [comment]
Hi @goodwilling, this is a Materials Project issue so would be better discussed at matsci.org/materials-project

In brief, we're going through a series of large database updates, including this week expanding our band structures (from 54k -> 76k) and drastically improving the quality of our densities of states (see the release notes on materialsproject.org). In the process we've introduce a bug, this bug is being fixed currently but it might take a day or two before this will work.
