### ISSUE TITLE
pymatgen warnings are immune to filtering

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#1954]
**Describe the bug**
Various warnings emitted by pymatgen appear to be immune to filtering by the normal python approaches like `warnings.simplefilter("ignore")` or the `catch_warnings` context manager.

**To Reproduce**

For example, instantiating `MPRester()` raises a `DeprecationWarning` due to the upcoming change in corrections classes. In some cases I want to suppress this warning; however the warning is still emitted by the following code blocks

```
import warnings
warnings.simplefilter("ignore")
with MPRester() as m:
    m.get_entries("Al2O3")
```

```
import warnings
with warnings.catch_warnings():
    with MPRester() as m:
        m.get_entries("Al2O3")
```

```
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(
                "ignore",
                message="MaterialsProjectCompatibility will be updated",
            )
    with MPRester() as m:
        m.get_entries("Al2O3")
```

```
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(
                "ignore",
                category=DeprecationWarning
            )
    with MPRester() as m:
        m.get_entries("Al2O3")
```

**Expected behavior**
Standard Python warning filtering mechanisms should work with pymatgen warnings.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 2020.09.14

**Comment by goodwilling** [comment]
The DeprecationWarning message can have unexpected side effects.

on Windows 10, I encountered a case where thousands of DeprecationWarning come out if executing a python library on a terminal: 

DeprecationWarning: species_and_occu is deprecated
Use site.species instead. This will be deprecated with effect from pymatgen 2020.

However, when the stdout/stderr of python is redirected to an input stream reader (buffered stream reader), 
no DeprecationWarning comes out but the execution of the python script just hangs there.
(Manual modification of the library by using site.species instead of site.species_and_occu 
solved the problem.)

**Comment by shyuep** [comment]
The problem was not in pymatgen, but in monty. The `@deprecated` wrapper has a warnings.simplefilter("default"), which overrides all other warnings filter calls. The reason this was done was because DeprecationWarning is ignored by default, and that is not the intent since we want users to change code to fix deprecated methods. 

In the end, I discovered that DeprecationWarning is not the correct class to use. It should be FutureWarning. I have updated monty to 4.0.1 and the following code works:

```python
from pymatgen import MPRester
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
mpr = MPRester()
print(mpr.get_entries("mp-19017"))
```

**Comment by rkingsbury** [comment]
Thank you @shyuep . So if I understand correctly we should still flag soon-to-be-deprecated code with `@deprecated`, but now it raises `FutureWarning` (which is filterable) and not `DeprecationWarning`?

**Comment by shyuep** [comment]
Yes use @deprecated. FutureWarning is meant for end users and is always emitted unless filtered. DeprecationMessage is meant for developers and is never emitted unless Python is run in developmental mode. So the correct one to use is FutureWarning, which is now used in the wrapper. To force DeprecationWarg to show, I overrode the filter in the wrapper, which was a bad idea.

**Comment by shyuep** [comment]
Just a small update. I updated the `@deprecated` method in monty v4.0.2 to allow a developer to specify the category of the warning. It defaults to FutureWarning, which I believe would be the most common use case. But in case you want to deprecate methods meant only for developers, this is something to consider.
