### ISSUE TITLE
The error description in the document for installation: pip install pymatgen[extra]

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1965]
Hi,

The document told the following:
```
$ egrep -inR 'pymatgen\[extra\]' .
./docs_rst/introduction.rst:182:   pip install pymatgen[extra]
```
But the output of the following installation command is not coherent with the above description: 
```
$ pip install .[extra]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Processing /home/werner/Public/hpc/tools/materialsproject/pymatgen.git
  WARNING: pymatgen 2020.9.14 does not provide the extra 'extra'
[...]
```
Any hints for this problem?

Regards,
HY

**Comment by mkhorton** [comment]
Here, "extra" is a placeholder for the specific "extra" that you require.

Currently, you can choose from "provenance", "ase", "vis" or "abinit" (see [here](https://github.com/materialsproject/pymatgen/blob/4b406abb589b9df1b7fbc3ba52e375f6fd3ed37e/setup.py#L115)).

As with the BoltzTrap2 dependencies, extras are optional. Most users do not need them.

**Comment by hongyi-zhao** [comment]
> Here, "extra" is a placeholder for the specific "extra" that you require.
> 
> Currently, you can choose from "provenance", "ase", "vis" or "abinit" (see [here](https://github.com/materialsproject/pymatgen/blob/4b406abb589b9df1b7fbc3ba52e375f6fd3ed37e/setup.py#L115)).

Do you mean any of them will do the trick, i.e., running one of the following:

```
$ pip install .[provenance]
$ pip install .[ase]
$ pip install .[vis]
$ pip install .[abinit]
```


> 
> As with the BoltzTrap2 dependencies, extras are optional. Most users do not need them.

**Comment by mkhorton** [comment]
The recommended way to install pymatgen is either:

`pip install pymatgen` (or, if you have a desired extra, `pip install pymatgen[provenance]` etc.)

or

`conda install -c conda-forge pymatgen`

If you are doing development, then you can manually install those dependencies yourself, such as doing `pip install -r requirements.txt`, but in general you only need to install dependencies for functionality you want to use. If you're not familiar with this additional functionality or you're not doing development using it, it's safe not to install it.

**Comment by hongyi-zhao** [comment]
> `pip install pymatgen` (or, if you have a desired extra, `pip install pymatgen[provenance]` etc.)

For my case, I run the command immediately under the local git repo root of pymatgen, so I think it should be invoked like the forms I posted previously.

> If you are doing development, then you can manually install those dependencies yourself, such as doing `pip install -r requirements.txt`, 

But the **requirements.txt** doesn't include any of these [packages](https://github.com/materialsproject/pymatgen/blob/4b406abb589b9df1b7fbc3ba52e375f6fd3ed37e/setup.py#L115).

  .[provenance]
$ pip install .[ase]
$ pip install .[vis]
$ pip install .[abinit]

**Comment by mkhorton** [comment]
Yes, that's correct, because these are optional requirements (hence "extras"), they are in `requirements-optional.txt`

Perhaps it would be useful to ask what you're intending to use pymatgen for, or why you're installing it? Typically, if you're new to pymatgen, I would recommend following the `pip install` or `conda install` instructions above, and not performing `git clone` etc.

The important thing is to understand that the `setup.py` and `requirements*.txt` files both describe similar things but with different purposes. The `setup.py` is generally used for installing, while the `requirements*.txt` give you specific known versions of dependencies, and can be useful for development. This structure is fairly typical for a Python code, and not specific to pymatgen itself.

**Comment by hongyi-zhao** [comment]
> Yes, that's correct, because these are optional requirements (hence "extras"), they are in `requirements-optional.txt`

But even the `requirements-optional.txt` doesn't include all the dependencies we discussed here.

**Comment by mkhorton** [comment]
I'm sorry, I'm not sure I understand the problem you're having. Pymatgen will work fine even if optional dependencies are not installed. If you find that you want to use a feature for which you don't have the requisite dependency, you will get a message and you can install it.

The `requirements-optional.txt` *does* have these optional dependencies, e.g. it has `pybtex` (the "provenance" extra), it has `ase` (the "ase" extra), it has `netcdf4` (the "abinit" extra), it does not have `vtk` but this is because vtk can be difficult to install on certain systems and is only used for the visualization package which is being deprecated.

**Comment by hongyi-zhao** [comment]
> The `requirements-optional.txt` _does_ have these optional dependencies, e.g. it has `pybtex` (the "provenance" extra), it has `ase` (the "ase" extra), it has `netcdf4` (the "abinit" extra), it does not have `vtk` but this is because vtk can be difficult to install on certain systems and is only used for the visualization package which is being deprecated.

Do you mean **vtk** is being deprecated by pymatgen?

**Comment by hongyi-zhao** [comment]
> The recommended way to install pymatgen is either:
> 
> `pip install pymatgen` (or, if you have a desired extra, `pip install pymatgen[provenance]` etc.)

There is still another question I can't figure out, see following for more info:

The following codes are the content of  [extras_require section of setup.py](https://github.com/materialsproject/pymatgen/blob/4b406abb589b9df1b7fbc3ba52e375f6fd3ed37e/setup.py#L115). So, if I want to install all of these extra dependencies in one run of pip, how should I invoke the pip command?

**Comment by mkhorton** [comment]
The correct pip install command would be `pip install pymatgen[provenance]` etc.

**Comment by hongyi-zhao** [comment]
> The correct pip install command would be `pip install pymatgen[provenance]` etc.

I'm still confused why can't I combine them in one like the following, considering that the usage should abide with the pip's specification:

`$ pip install .[provenance,ase,vis,abinit] `
