### ISSUE TITLE
Calculated energy is not same with MP

### ISSUE THREAD

**Issue by haesunpark87** [materialsproject/pymatgen#1998]
I have calculated the energy of Li2O using the input setting made by **MPRelaxSet** module from pymatgen. 
However, the calculated energy is way off from that in the MP data base(https://materialsproject.org/materials/mp-1960/#corrections-eqn).
The uncorrected energy differs by ~30meV/atom. 
I used the POTCAR of Li_sv and O which are specified by pymatgen code and attempts with the different versions of vasp did not fix the issue. 
I'm wondering what make this discrepancy and I attach the standard output(stdout_1), vasprun.xml file, and the python script generating the vasp inputs (vasp_input.py) for reference. 

[outputs.tar.gz](https://github.com/materialsproject/pymatgen/files/5554990/outputs.tar.gz)

**Comment by chc273** [comment]
@haesunpark87 I recently noticed the same issue. The problem was due to the different pseudopotentials used for Li_sv. The PAW_PBE Li_sv in MP should be the `23Jan2001` version. Maybe the Li_sv you are using was `10Sep2004`. @mkhorton Is this something significant? I also have friends who had the same issues and spent days debugging.

**Comment by mkhorton** [comment]
I'm looking into it, it's difficult to debug this kind of issue, I will say that the MP database is by no means perfect and we have encountered changes in energy in non-deterministic ways which is always troubling, as a result of different VASP compilations, parallelization settings, etc.

However, I re-ran the attached input and got the following as the final step:

```
   3 F= -.14263627E+02 E0= -.14263627E+02  d E =-.663574E-04  mag=    -0.0000
```

vs the output from @haesunpark87:

```
   3 F= -.14347976E+02 E0= -.14347976E+02  d E =-.283537E-02  mag=    -0.0000
```

@haesunpark87 My repeat is 80 meV different from your output but only 3 meV different from the MP database so perhaps you're using different pseudo potentials? Also a small note on your script, you should be careful not to paste the API key publicly, and `str` is not a good variable name for a structure since it shadows the built-in Python string type (`str`).

@chc273 please do let us know if anyone is spending days debugging, would definitely like to help if we can to save time.

**Comment by haesunpark87** [comment]
I'm sorry to confusion, but I've been using wrong version of POTCAR.
The calculation which yields 30meV/atom discrepancy was done with POTCAR version of potpaw_PBE.52 which is not compatible with MP data base. Once I switch to POTCAR version to potpaw_PBE, the result was very similar to MP data base.

**Comment by mkhorton** [comment]
Glad to hear you figured it out :)
