### ISSUE TITLE
Composition shows weird things when reading in unknown element

### ISSUE THREAD

**Issue by TimoSommer** [materialsproject/pymatgen#2038]
**Describe the bug**
When I make a new Composition from a string that contains a chemical formula with non valid (but still often e.g. as placeholder used symbols) like "M", this pseudo element gets represented with the string "M0+" which is not the expected behaviour.

**To Reproduce**
import pymatgen
string = M2         # Notice M is no valid chemical element
comp = pymatgen.Composition(string)      

If one inspects comp then you see that the element "M" somehow is represented as "M0+". You can for example easily see this by getting the dictionary
comp_dict = comp.as_dict()       # comp_dict = defaultdict(<class 'float'>, {'M0+': 2.0})

**Expected behavior**
I would expect that though this element is not valid, it still shows up as "M" and not as "M0+". For example, when using the method Composition.as_dict() there should be a key "M" and not a key "M0+".

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1 Cinnamon
 - Version: 2020.12.31

**Comment by shyuep** [comment]
This is a feature, not a bug. It is common practice to use symbols to represent abstract species, e.g., vacancies or just some group of elements.

**Comment by mkhorton** [comment]
For more context on this, read the documentation on `DummySpecies`. It is possible to initialize a DummySpecies without oxidation state, e.g. `DummySpecies('M', oxidation_state=None)` but this has to be done manually. When initializing a `Composition` from a string, the string is parsed and a best guess is taken (historically, a 0 oxidation state is assigned because Species used to require an oxidation state, but this is now optional -- the old behavior was retained so as not to break backwards compatibility).

**Comment by TimoSommer** [comment]
Alright, so this is historic behaviour. Thank you very much for clearing this up!
