### ISSUE TITLE
pymatgen.analysis.defects.point_defects doesn't exist

### ISSUE THREAD

**Issue by yurivict** [materialsproject/pymatgen#2073]
This command from the manual @ https://pymatgen.org/installation.html fails:
```
$ python3.7
Python 3.7.9 (default, Dec 12 2020, 01:25:17) 
[Clang 8.0.1 (tags/RELEASE_801/final 366581)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>>  from pymatgen.analysis.defects.point_defects import Interstitial
  File "<stdin>", line 1
    from pymatgen.analysis.defects.point_defects import Interstitial
    ^
IndentationError: unexpected indent
>>> 
```

Version 2021.2.16

**Comment by mkhorton** [comment]
It's because you copied it with an extra space at the start :-) This is generally true wherever you copy and paste Python code, be careful of leading tabs or spaces. I would recommend reading some general Python tutorials before getting started with pymatgen specifically.

That example is out of date for a separate reason however, it should now read:

```
from pymatgen.analysis.defects.core import Interstitial
```

You can check the API docs for more information on specific classes, such as this page for the [`Interstitial`](https://pymatgen.org/pymatgen.analysis.defects.core.html#pymatgen.analysis.defects.core.Interstitial) object.
