### ISSUE TITLE
Please don't deprecate latexify

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#2098]
The `latexify`, `unicodeify`, etc have been deprecated in a recent update. We are now recommended to use the `Stringify` mix-in class.

Please can you not remove these functions. I use them fairly extensively in my code and in many cases switching to the `Stringify` mix-in class is not possible. For example, I have a string "n-CH3NH3PbI3". There is no way to convert this to a latex string directly using the mix-in class, whereas `latexify("n-CH3NH3PbI3")` gives the output I'd expect: `"n-CH$_3$NH$_3$PbI$_3$`.

If you'd like to remove the duplication, I'd recommend that the `Stringify` mix-in class use these functions directly rather than duplicating the code in both places.

**Comment by mkhorton** [comment]
Ok, this sounds fair to me, I can definitely see how these might be useful for people for formula strings that cannot be cast to Composition.

> If you'd like to remove the duplication, I'd recommend that the Stringify mix-in class use these functions directly rather than duplicating the code in both places.

This seems like the best solution. We can retain the benefits of `Stringify` and use this going forwards while keeping these around for use cases like yours. Tagging @shyuep here in case there are objections.

If you'd like to submit a PR, please do so, otherwise I'll add it to my list of items next time I'm doing pymatgen maintenance work.

**Comment by utf** [comment]
Ok, thanks. I will submit a PR.

**Comment by mkhorton** [comment]
This was done (deprecation notice removed) so closing the issue.
