### ISSUE TITLE
NaN should be removed from any init functions

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/pymatgen#2107]
An example is shown here:

https://github.com/materialsproject/pymatgen/blob/04beca9af8e575005a40117f1779f1d464c0a697/pymatgen/entries/computed_entries.py#L49

I think these should be removed from any MSONable init function since they don't play well with database and model validation.
I'm currently just replacing these with 0's in any emmet model that contains `ComputedEntry`s 

https://github.com/materialsproject/emmet/blob/ebcc50bc47a8b65d661877f9edeb7f4087a7b4e5/emmet-core/emmet/core/utils.py#L117

but if the NaN's are physically meaningful I think we need to replace them with `None`.

@mkhorton @rkingsbury @shyamd

**Comment by janosh** [comment]
Using `None` instead of `np.nan` seems like a safe-enough change. PR incoming.

**Comment by janosh** [comment]
Looks like `uncertainty` isn't able to handle `None`:

```py
>       if std_dev < 0 and not isinfinite(std_dev):
E       TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

@jmmshn Would `float("nan")` play better with database validation with `np.nan`? I suspect it might be the same.

**Comment by jmmshn** [comment]
So looks like this happened in the mean time?
https://github.com/materialsvirtuallab/monty/pull/379

**Comment by janosh** [comment]
@jmmshn Thanks for the monty link. That's good context to have!

@rkingsbury Do you anticipate any issues with using `math.inf` instead of `np.nan` as default uncertainty value? `math.inf` seems less semantic for a missing value.

**Comment by janosh** [comment]
> I would use None when uncertainty was not computed at all.

Same. That's what I did yesterday in https://github.com/materialsproject/pymatgen/pull/3021 but doesn't work with the [`uncertainties` lib](https://pypi.org/project/uncertainties).


```py
std_dev = None

    @std_dev.setter
    def std_dev(self, std_dev):
    
        # We force the error to be float-like.  Since it is considered
        # as a standard deviation, it must be either positive or NaN:
        # (Note: if NaN < 0 is False, there is no need to test
        # separately for NaN. But this is not guaranteed, even if it
        # should work on most platforms.)
>       if std_dev < 0 and not isinfinite(std_dev):
E       TypeError: '<' not supported between instances of 'NoneType' and 'int'

/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/uncertainties/core.py:2798: TypeError
```

**Comment by shyuep** [comment]
I guess I don't understand what mathematical operations can be performed logically on an unknown uncertainty. It is like saying the uncertainty is the word "nothing" and I am performing a mathematical operation on "nothing" and a number. For logical uncertainties, either all values in the chain have well-defined uncertainties or the whole operation has no output.

**Comment by shyuep** [comment]
Sorry but what is the max of 1, 2 and NaN in logical terms?

**Comment by awvio** [comment]
I think the main reason we went with `np.nan` instead of `None` is because of the practical reason that `None` doesn't work with the ufloat class. In general, I believe `None` doesn't work well with mathematical operations - as shown in by Janosh's example with the `max()` function. Another example of where `np.nan` works better for us than `None` is when we calculate the average uncertainty of a set of experimental energies. We can use `np.nanmean()` to straightforwardly calculate the average uncertainties, ignoring the unknown uncertainties that have been set to `np.nan`.

**Comment by janosh** [comment]
@awvio Makes sense to me.

All things considered, esp. that https://github.com/materialsvirtuallab/monty/pull/379 now handles NaN more gracefully as @jmmshn pointed out, I think the status quo is actually fine. Let's close this without any changes. Happy to reopen if anyone feels strongly otherwise.
