### ISSUE TITLE
Question on TEM diffraction calculator

### ISSUE THREAD

**Issue by YuLin999** [materialsproject/pymatgen#2153]
I am trying to generate some simulation diffraction pattern data using and got some patterns inconsistent with the real patterns. Wondering if I was doing this correctly. Here is the codes that I used (and the generated pattern is attached). mp-13 is Fe with cubic bcc structure so I am expecting the simulated pattern will has 4-fold symmetry.
    
        structure = mpr.get_structure_by_material_id('mp-13')
        calculator = tem.TEMCalculator(beam_direction=[1,0,0])
        fig = calculator.get_plot_2d(structure=structure)
        fig.show()

![newplot (2)](https://user-images.githubusercontent.com/44076136/119399197-38478d00-bc9e-11eb-95e7-5aaba2d8f4b2.png)

**Comment by utf** [comment]
The issue is that `mpr.get_structure_by_material_id` will download the primitive cell structure by default. This means that the [1, 0, 0] direction in your structure does not correspond to the [1, 0, 0] of the conventional cell but instead the [1, 1, 1] of the conventional cell.

Asking for the conventional cell gives the correct 4-fold symmetry.

```python
from pymatgen.ext.matproj import MPRester
from pymatgen.analysis.diffraction.tem import TEMCalculator

structure = mpr.get_structure_by_material_id('mp-13', conventional_unit_cell=True)
calculator = TEMCalculator(beam_direction=[1,0,0])
plt = calculator.get_plot_2d(structure=structure)
plt.show()
```

<img width="556" alt="Screenshot 2021-05-24 at 13 53 37" src="https://user-images.githubusercontent.com/1330638/119406543-d1bf7080-bc97-11eb-9383-3bdc1b6d1348.png">

**Comment by shyuep** [comment]
@utf [100] in primitive cell is not [111] in the conventional either. In cubic system, the [111] remains [111] in both conventional and primitive.

**Comment by shyuep** [comment]
Actually wait.. for bcc, the primitive [100] is the [111]. You are right. It is for fcc that the [111] remains the same.

**Comment by YuLin999** [comment]
Okay I see. Thanks a lot for the quick response!!
