### ISSUE TITLE
unexpected result of get_conventional_standard_structure() to mp-644693

### ISSUE THREAD

**Issue by lwk8891** [materialsproject/pymatgen#2155]
**Describe the bug**
The get_conventional_standard_structure() method of pymatgen.symmetry.analyzer.SpacegroupAnalyzer class changes the atomic connection of mp-644693.

**To Reproduce**
1. get the structure of mp-644693 by calling s=get_structure_by_materials_id('mp-644693') of pymatgen.ext.matproj.MPRestrer class
2. Create the SpacegroupAnalyzer class for structure s by anal=SpacegroupAnalyzer(s)
3. Get the conventional standard structure by conv_struct=anal.get_conventional_standard_structure()
4. Visualize the structures s and conv_struct by making POSCAR format of VASP, then the atomic connections are different

**Expected behavior**
The atomic connection is maintained after getting conventional standard structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/81547431/119791034-68e22d80-bf0f-11eb-9b94-c961ee8ac6ff.png)

**Additional context**

**Comment by mkhorton** [comment]
Thanks @lwk8891, this is almost certainly a serious bug. I will investigate.

For now, I suggest you use `.get_refined_structure()` which might work for your purposes.

**Comment by ehofgard** [comment]
Has this issue been resolved?

**Comment by fraricci** [comment]
Hi!

I quickly checked the original issue and could not reproduce it.
I get the same structure for mp-644693 after using the get_conventional_standard_structure(). There is just a swap of the a and b axes, 
but the structure is the same. This swap is due to the "convention" used in the definition
of the cell as reported in the doc of the function:
```
Gives a structure with a conventional cell according to certain
standards. The standards are defined in Setyawan, W., & Curtarolo,
S. (2010). High-throughput electronic band structure calculations:
Challenges and tools. Computational Materials Science,
49(2), 299-312. doi:10.1016/j.commatsci.2010.05.010
They basically enforce as much as possible
norm(a1)<norm(a2)<norm(a3). NB This is not necessarily the same as the
standard settings within the International Tables of Crystallography,
for which get_refined_structure should be used instead.
```


In your case, there is a similar swap of the a and b axes, but I'm guessing the structure
is the same. The small difference in the decimal digits could come from the fact that
the ICSD is the exp. structure while the stucture from MP is relaxed.

Hope this helps.

**Comment by fraricci** [comment]
well, `get_conventional_standard_structure()` follow the convention in Setyawan, W., & Curtarolo,
S. (2010); whereas the `get_refined_structure()` follows the International Tables of Crystallography ;-)
I'm not sure about which convention is used in ICSD, it might be neither of the above.

**Comment by arosen93** [comment]
@janosh: Looks like this can be closed based on @fraricci's analysis.
