### ISSUE TITLE
Inefficient k-point generation for NiO (and possibly other structures)

### ISSUE THREAD

**Issue by ab5424** [materialsproject/pymatgen#2162]
**Describe the bug**
When using the NiO structure (mp-19009) from the MP, the generation of k-points in VASP is inefficient.

**To Reproduce**
Using 
```
with MPRester() as a:
    struct = a.get_structure_by_material_id('mp-19009')

relax = MPRelaxSet(structure=struct,
                   user_kpoints_settings={"grid_density": 2000},
                   force_gamma=True)
```

yields 115 irreducible k-points in the calculation:

`Found    115 irreducible k-points:` (from OUTCAR)

**Expected behavior**
When using the POSCAR provided by the VASP manual (https://www.vasp.at/wiki/index.php/NiO), I get 44 irreducible k-points, with otherwise identical settings.

`Found     44 irreducible k-points:`

This is attributed to the different meshes in the k-point files (`Gamma 9 9 5` for MP structure vs `Gamma 7 7 7` for VASP structure). This isn't really a bug but it seems quite inefficient to me (I stumbled across this when carrying out HSE calculations). I'm also not sure if that only affects this structure or others as well.

**Comment by shyamd** [comment]
You didn't use the default `grid_density`, so you're getting a k-point mesh commensurate with that. If you want a smaller k-point mesh, then set `grid_density` to a smaller number. 

Also, that is an example calculation from the VASP manual. It is not in any way a recommendation on k-point density. That you have to decide based on what you want to do.

**Comment by ab5424** [comment]
Sorry @shyamd, I probably wasn't precise enough. I did two calculations with **exactly the same settings**, one with the structure from the MP and one with the structure from VASP, like this:

```
with MPRester() as a:
    struct_MP = a.get_structure_by_material_id('mp-19009')
relax = MPRelaxSet(structure=struct_MP)
relax.write_input("struct_MP")


struct_VASP = Structure.from_file('NiO-VASP-POSCAR') #  This is the structure from the VASP website
relax = MPRelaxSet(structure=struct_VASP)
relax.write_input("struct_VASP")
```

With the structure from the MP, I got `Gamma 9 9 5` and with the VASP structure I got `Gamma 7 7 7` in the `KPOINTS` file, with the latter being far more efficient, as I explained in my first post. (In this case, changing the grid setting didn't influence the setup.) 

The issue seems to be the initial cell vectors. I'm not sure if that affects other compounds with the same structure type but saving ~62% of computing time by changing the orientation of the vectors seems a lot to me. I'm currently calculating phonons where I need very accurate forces, so I have to use strict (and expensive) convergence criteria. I also used `StructureMatcher` to verify that both structures are the same.

**Comment by shyamd** [comment]
This is a difficult problem. It's hard to tell apriori which setting will be the fastest. Sometimes you can get lower k-points, but that will result in slower electronic convergence. Depending on what the user is doing it's possible the settings are purposely in a setting that's not ideal. The `InputSet` respects whatever structure the user provides and its up to the user to optimize the settings. 

MP's audience isn't just researchers using DFT. We choose to put structures in a conventional standard-setting to make the structure easily interpretable.

**Comment by mkhorton** [comment]
@ab5424 are you saying that both cases have equivalent numbers of overall k-points, but a difference in the number of irreducible k-points due to a difference in crystallographic setting?

**Comment by ab5424** [comment]
@mkhorton It's almost the same overall number (9*9*5= 405, 7*7*7=343), due to rounding. But yes, that was what i tried to say, due to the different lattice vectors, the number of irreducible k-points differ significantly.

@shyamd I assume that it's best for any code to use an input structure that is as symmetric as possible, in any aspect. The "VASP website" structure has reciprocal lattice vectors with equal length, the MP structure does not:

VASP:
```
  direct lattice vectors                    reciprocal lattice vectors
     4.170000000  2.085000000  2.085000000     0.359712230 -0.119904077 -0.119904077
     2.085000000  4.170000000  2.085000000    -0.119904077  0.359712230 -0.119904077
     2.085000000  2.085000000  4.170000000    -0.119904077 -0.119904077  0.359712230

  length of vectors
     5.107186114  5.107186114  5.107186114     0.397676833  0.397676833  0.397676833
 ```

MP:
```
  direct lattice vectors                    reciprocal lattice vectors
     2.109361000 -0.000052000 -2.109347000     0.355613956 -0.118450847 -0.118461130
     0.000054000 -2.109368000  2.109347000     0.118451353 -0.355612888  0.118460906
    -2.105111000 -2.105116000 -4.214497000    -0.118699391 -0.118699109 -0.118697252

  length of vectors
     2.983077035  2.983081985  5.159940955     0.393096589  0.393095708  0.205591978
```

The volume is the same, the positions are the same etc. Is there any way to construct the structure with equally long (reciprocal) lattice vectors, and would that conflict with the MP's standard settings?

**Comment by mkhorton** [comment]
I would offer a few general points. This doesn't respond to your issue directly Alexander, but might help elucidate:

* The MP standard settings (our current defaults) are comparatively old, so don't necessarily reflect best practices _today_
* Newer MP data (not yet released) is using KSPACING as default rather than this method, you can check out the MPScanSet as an example of how we're using this -- our new scheme is using a KSPACING that is band-gap dependent
* For an arbitrary material, it is very difficult to know in advance which setting would give the optimal k-point grid if using the Monkhorst-Pack algorithm
* However, to address this, there are now even better methods available, e.g. see generalized k-point grids in [this paper](https://doi.org/10.1016/j.commatsci.2020.110100) and [this paper](https://doi.org/10.1016/j.commatsci.2019.109340). Code exists for both. In pymatgen, we had an interface to the k-point generation API in `pymatgen.ext.jhu`, but both groups now offer local codes that can be used instead. I believe the former integrates nicely with pymagen already (@shyamd might comment further, given that he's on the former paper).

> The volume is the same, the positions are the same etc. Is there any way to construct the structure with equally long (reciprocal) lattice vectors, and would that conflict with the MP's standard settings?

To this point, what you probably want is the LLL reduced structure. There is a method on the `Structure` object that can give you this. This applies a fast algorithm that gives lattice vectors that likely are as orthogonal as possible. It does not _guarantee_ to fulfill this condition, but algorithms that do this rigorously are that much slower, and the LLL reduced lattice is almost always "good enough."

**Comment by ab5424** [comment]
@mkhorton Thanks for the clarification. I guess NiO is a special case due to the AFM structure. For now, `KSPACING` might be a better option when writing new input sets and I will try this for my phonon calculations.
