### ISSUE TITLE
Significantly different Pourbaix diagrams somewhere between 2020.3.13 and 2022.0.8

### ISSUE THREAD

**Issue by mwitman1** [materialsproject/pymatgen#2173]
**Describe the bug**
There seems to significant difference in the Pourbaix diagrams generated in 2022.0.08 and those up to at least v2020.3.13. I’m referencing v2020.3.13 because it’s the last version in the Change Log that makes a mention of “pourbaix”. Ultimately it seems to come down to the computed energies for each species in the diagram between the two versions, some of which are quite large (up to 1 ev/atom).

**To Reproduce**
```
from pymatgen.ext.matproj import MPRester
from pprint import pprint
from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter

with MPRester(APIKEY) as mpr:
    pourbaix=mpr.get_pourbaix_entries(['Cu'])

def f(lst):
    “”” pretty prints the most stable entry for a given compound “””
    lst = [(entry.composition.reduced_formula, entry.energy_per_atom) for entry in lst]
    d = {}
    for tup in lst:
        if tup[0] not in d.keys():
            d[tup[0]]=tup[1]
        elif tup[1] < d[tup[0]]:
            d[tup[0]] = tup[1]
    return d

pprint(f(pourbaix))
pbx = PourbaixDiagram(pourbaix)
plotter = PourbaixPlotter(pbx)
plotter.get_pourbaix_plot().show()
```

**Expected behavior**
In **v2020.3.13** I get the following, and the pourbaix diagram is pretty close to what appears on the web app, although not quite identical:
{'Fe': -1.622125307056931,
 'Fe(HO)2': -0.08565486141138604,
 'Fe(HO)3': -0.037704901008132855,
 'Fe10O11': -0.272528083333333,
 'Fe11O12': -0.27000459956521927,
 'Fe12O13': -0.23810561700000094,
 'Fe13O14': -0.2507718170370378,
 'Fe13O15': -0.22857405517857185,
 'Fe13O19': 0.053782962968749404,
 'Fe14O15': -0.2649596684482761,
 'Fe15O16': -0.24799346483870952,
 'Fe17O18': -0.2864528791428575,
 'Fe21HO32': -0.04000913377074037,
 'Fe21O23': -0.2655534476136363,
 'Fe21O32': -0.019029330943396604,
 'Fe23O25': -0.2702020153125,
 'Fe23O32': -0.1528225829090913,
 'Fe25O32': -0.09684627649122858,
 'Fe2O3': -0.2420518570000006,
 'Fe2O5': 0.9901734950000005,
 'Fe32O35': -0.26137829828358267,
 'Fe35O36': 0.45011210830985887,
 'Fe38O39': -0.262887671623377,
 'Fe3H': 1.1950894790949995,
 'Fe3O': 1.1023692849999995,
 'Fe3O4': -0.2570221514285707,
 'Fe41O56': -0.17948183690721772,
 'Fe43O64': -0.12777606065420513,
 'Fe4H14O13': 1.0941170194941923,
 'Fe4O13': 1.5738661873529407,
 'Fe4O5': -0.1980533911111119,
 'Fe5HO8': 0.05780113652714368,
 'Fe5O7': -0.0888776762499992,
 'Fe5O8': 0.036853481730769196,
 'Fe7O8': -0.2445972323333334,
 'Fe7O9': -0.06110978593750005,
 'Fe8H10O17': 0.6559708343942865,
 'Fe8O17': 0.6088237528000002,
 'Fe8O9': -0.26275042058823506,
 'Fe9O10': -0.2755539805263164,
 'Fe9O13': 0.012218070227270868,
 'FeH': 1.1894350456899998,
 'FeH3': 2.034037118535,
 'FeH4': 2.227225052104,
 'FeHO': -0.4067181023523105,
 'FeHO2': 0.049041423235767434,
 'FeO': -0.3401552675000008,
 'FeO2': 0.09847189764768978,
 'FeO3': 1.4467245549999985,
 'FeO4': 1.1378171385886138}

<img width="992" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/10645657/121747165-d075ac80-cabb-11eb-8e77-df79a4b0e1a8.png">

Whereas in **v2022.0.8** I get the following. There is a very large discrepancy in the energies of various compounds including (especially H containing and even Fe itself), while some others seem to be relatively close. But it has a significant impact on the diagram. Would it be possible for the Materials Project team to trouble shoot this issue? Is this something to do with new data on MP or pymatgen processing of the pourbaix entries being incorrect in the newest version?

{'Fe': -1.1221903070569303,
 'Fe(HO)2': 0.014332138588614107,
 'Fe(HO)3': 0.033714384706152956,
 'Fe10O11': -0.03737617857142726,
 'Fe11O12': -0.033896773478261984,
 'Fe12O13': -0.0011948170000003699,
 'Fe13O14': -0.013177002222222607,
 'Fe13O15': 0.0010813019642864471,
 'Fe13O19': 0.25664265046874957,
 'Fe14O15': -0.02677518568965515,
 'Fe15O16': -0.009295400322580307,
 'Fe17O18': -0.04690373628571385,
 'Fe21HO32': 0.1409162460185182,
 'Fe21O23': -0.02990185670454518,
 'Fe21O32': 0.17920236716981103,
 'Fe23O25': -0.03367597364583327,
 'Fe23O32': 0.05554614436363517,
 'Fe25O32': 0.12094810947368503,
 'Fe2O3': -0.04207785700000031,
 'Fe2O5': 1.1373806378571427,
 'Fe32O35': -0.025570089328357977,
 'Fe35O36': 0.6930056294366199,
 'Fe38O39': -0.019740788506492496,
 'Fe3H': 0.7268496062499992,
 'Fe3O': 1.4639417849999998,
 'Fe3O4': -0.04385643714285666,
 'Fe41O56': 0.03096393628865947,
 'Fe43O64': 0.0730609486915891,
 'Fe4H14O13': 0.829550475,
 'Fe4O13': 1.697793834411764,
 'Fe4O5': 0.02244105333333203,
 'Fe5HO8': 0.18430188714285656,
 'Fe5O7': 0.11879149041666744,
 'Fe5O8': 0.22972425096153898,
 'Fe7O8': -0.013842565666666692,
 'Fe7O9': 0.15617833906249956,
 'Fe8H10O17': 0.5620518368571433,
 'Fe8O17': 0.7718609528000002,
 'Fe8O9': -0.03018512647058813,
 'Fe9O10': -0.04155924368421145,
 'Fe9O13': 0.2163894338636359,
 'FeH': 0.2529553,
 'FeH3': 0.6293175000000009,
 'FeH4': 0.7288574589999989,
 'FeHO': -0.24007310235231025,
 'FeHO2': 0.17402517323576738,
 'FeO': -0.09401026750000052,
 'FeO2': 0.2651168976476897,
 'FeO3': 1.5547095549999987,
 'FeO4': 1.2378041385886138}

<img width="987" alt="10 12 14" src="https://user-images.githubusercontent.com/10645657/121747138-c6ec4480-cabb-11eb-8fe2-1b0b901328c2.png">

**Comment by mkhorton** [comment]
Hi @mwitman1, please see the Materials Project database release notes here for more information: https://matsci.org/t/materials-project-database-release-log/1609/18

@rkingsbury can comment further (though he's not available this week, so may take some time for a response)

**Comment by mwitman1** [comment]
Hi @rkingsbury thanks for looking into it whenever you have some time, and sorry in the first post also wanted to highlight how the Materials Project web app still seems to be more consistent with the previous 2020.03.13 version at more reducing potentials, if you have any comment on that as well

<img width="857" alt="image" src="https://user-images.githubusercontent.com/10645657/121938710-00fa5800-cd01-11eb-9903-36b69a9db6a1.png">

**Comment by rkingsbury** [comment]
Hi @mwitman, thanks for reporting. The discrepancy you found between your code and the website is due to the fact that we set the `filter_solids=True` kwarg when instantiating `PourbaixDiagram`, e.g.

```
pbx = PourbaixDiagram(pourbaix, filter_solids=True)
```

 `filter_solids=True` includes only solid entries that are stable on the compositional phase diagram when it constructs the Pourbaix diagram, whereas with `filter_solids=False`, even unstable solid polymorphs are included in the diagram. That can at times lead to strange results.

 To be honest, `filter_solids=True` should probably be the default because we consider that to be the most correct way to build these diagrams and that is what we use on the website. @montoyjh , do you have any further comments on this?

I think the differences in energy you saw among some materials between your two versions are an artifact of a transitional period in our database release cycle (i.e., `get_pourbaix_entries` using legacy corrections even though the database was updated with new energies), so I wouldn't worry about that.

Hope this helps! I'm going to close for now but feel free to reopen if you think there's still a bug here.

**Comment by montoyjh** [comment]
Yeah, my opinion is that `filter_solids=True` is the most correct way to represent equilibrium phase stability.  The practical consequence of this is that highly oxidized or reduced phases that might show up in experiments due to kinetic limitations on oxygen/hydrogen evolution won't appear, but they're not actually "stable" (and are frequently overstabilized from DFT errors).  I'd keep the option to not filter, but would be happy to see the default change to be consistent with the Materials Project website.
