### ISSUE TITLE
Convert XYZ to cif format

### ISSUE THREAD

**Issue by VictorPullzz** [materialsproject/pymatgen#2180]
**Describe the bug**
Hello I have a question. How I can convert XYZ file to cif format?
For ex:
I have some XYZ file 
![image](https://user-images.githubusercontent.com/23406402/123007801-6e258180-d3c2-11eb-9b55-bda0fe8bf23c.png)
I need convert this to cif format  file.
How I can doing this?
Pelase help me)

**Comment by mkhorton** [comment]
Hi @VictorPullzz, since this is not a bug, you would be better off asking for help at our discussion forum: matsci.org/pymatgen

In brief, the CIF format is a crystallographic format, meaning it also defines a periodic lattice. XYZ files typically describe molecules, although some have a header with lattice information. To convert to CIF, import the XYZ file (e.g. using `Molecule`), construct a `Structure` object with the appropriate `Lattice`, and then use `Structure.to(filename="your_file.cif")` to export.

**Comment by VictorPullzz** [comment]
@mkhorton Hello thanks for you anwser, please can you send me example, how I can do it )))
