### ISSUE TITLE
checking whether an entry is stable makes getting `e_above_hull` O(N) as opposed to O(1)

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2181]
https://github.com/materialsproject/pymatgen/blob/f091ddba0a82c586eca91b454ebeeafb45ac80fe/pymatgen/analysis/phase_diagram.py#L566-L569

In `PhaseDiagram.get_decomp_and_e_above_hull` the current code first checks if an entry is in the stable entries. This wastes a large amount of compute to ensure that the decomp is exactly 1 as opposed to 1.0000000000000002 which is what we get from the bary_coord calculation for stable entries. 

Removing this check speeds up my workflow by several hours and I think it would be sensible to remove it from the dev branch also.

**Comment by shyuep** [comment]
Thanks for reporting this. Can you provide an actual profile code showing this is indeed the offending line? I would assume a quick search through stable entries would be faster than doing the actual decomp computation for stable entries. Of course, if you have 100000 unstable entries and only 10 stable entries, that may result in a lot of unnecessary checks.

A few things we can do:
1. Swap the order of the entry `__eq__` checks - I believe checking entry_id first might be faster than checking energy or composition since that is usually just a string. - I just pushed a change to implement this.
2. We can add a boolean parameter called `skip_stable_check` to bypass that if statement. It is up to the user to then make sure they do the checks themselves.

@rkingsbury @mkhorton Pls comment.

**Comment by CompRhys** [comment]
I am currently refactoring code to try before releasing the source and so my workflow is currently broken but I will post come profiling results once I have it working again. 

The workflow was looking at the stabilities of randomly generated structures (initial screening library ~400k) against a patched phase diagram of MP + the MP compatible data from https://archive.materialscloud.org/record/2021.68.

**Comment by shyuep** [comment]
@rkingsbury One thing to consider is whether we want ot make the entry id check *exclusionary* rather than inclusionary,. Right now, the check says that if the entry ids are equal, we set to True. If not, we check composition and energy. Given that most entries are UNEQUAL, we can say that if entry ids exist and are not equal, we return False without checking composition or energy. I believe that will make the entry check basically many times faster.

**Comment by CompRhys** [comment]
@shyuep on this front what would your opinion be on adding entry_ids to `PDEntry` and it's children and removing reference to the class in the `__hash__` for entry type objects? 

This would allow another hack(?) i've done using `PDEntry` in the pd construction but computing the properties of `ComputedStructureEntries` from the second data set to become standard. Using `PDEntry` helps a fair amount with speed as returning the energy becomes a look-up rather than a function call with the corrections.

**Comment by shyuep** [comment]
I would generally avoid adding entry ids to PDEntry. I prefer to keep objects to their *minimum required specification*. When you add something like entry ids to an object, you are imposing a requirement for the user to properly designate such ids. If someone were to say, just set `entry_id = 1` for all the entries he creates, that would result in wrong behavior. If you were going to just assign a unique number to each PDENtry you create, that would be no different from the `object._id` that comes part and parcel of every Python object. In essence, you are replicating default functionality already present.

For computed entries, this is more justifiable since we have things like MP that assigns unique ids.

**Comment by shyuep** [comment]
@CompRhys I had a thought that if you are going to generate a lot of entries from your own vaspruns, it would be helpful if a default entry_id is added to get_computed_entry. I have just pushed a change that implements this. What this means is that all computed entries generated from your own Vaspruns would now have a entry id "vasprun-{datetime that it was parsed}". This would at the very least ensure that almost all ComputedEntries have a valid entry_id, which would speed up the checks a lot.

**Comment by rkingsbury** [comment]
I will defer to you guys on this one; this is beyond the extent of my software engineering knowledge.

**Comment by CompRhys** [comment]
@shyuep have fixed the workflow and an profiling now. Removing the check getting e_above_hull for all ternaries and below from my `PatchedPhaseDiagram` takes ~ 97 seconds whilst with the check it will take ~60 hours. This is very extreme as the `stable_entries` of the `PatchedPhaseDiagram` covers all the patches not just the individual patch (i.e. `PhaseDiagram`) being considered in each chemical system.

**Comment by shyuep** [comment]
Thanks. Can you paste the output of the profiling here? I am curious which function call is causing that speed difference.

**Comment by CompRhys** [comment]
Sure, because I don't want to wait 60 hours with check is just for 100 entries whilst without check is for all 84944 tertiary or smaller systems.

The vast majority of the time is spent checking the equality of `ComputedEntries`.

[with_check.txt](https://github.com/materialsproject/pymatgen/files/6727035/with_check.txt)
[without_check.txt](https://github.com/materialsproject/pymatgen/files/6727036/without_check.txt)

**Comment by shyuep** [comment]
Did you update with the latest pymatgen yet? 

```python
from pymatgen.ext.matproj import MPRester
from pymatgen.analysis.phase_diagram import PhaseDiagram

mpr = MPRester()
entries = mpr.get_entries_in_chemsys(["Li", "Fe", "P", "O"])
pd = PhaseDiagram(entries)

def main():
    return [pd.get_decomp_and_e_above_hull(e) for e in entries]

if __name__ == "__main__":
    import cProfile
    import os
    import pstats
    cProfile.run('main()', 'profile_stats')
    p = pstats.Stats('profile_stats')
    p.sort_stats('cumulative').print_stats(20)
    os.remove("profile_stats")
```

This is my profiling code. The output is:

```
         664439 function calls (658491 primitive calls) in 0.325 seconds

   Ordered by: cumulative time
   List reduced from 73 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.326    0.326 {built-in method builtins.exec}
        1    0.000    0.000    0.326    0.326 <string>:1(<module>)
        1    0.000    0.000    0.326    0.326 /Users/sp/Library/Mobile Documents/com~apple~CloudDocs/Downloads/py/profilepd.py:20(main)
        1    0.000    0.000    0.326    0.326 /Users/sp/Library/Mobile Documents/com~apple~CloudDocs/Downloads/py/profilepd.py:21(<listcomp>)
      943    0.002    0.000    0.326    0.000 /Users/sp/repos/pymatgen/pymatgen/analysis/phase_diagram.py:549(get_decomp_and_e_above_hull)
      943    0.002    0.000    0.255    0.000 /Users/sp/repos/pymatgen/pymatgen/analysis/phase_diagram.py:520(get_decomposition)
      879    0.009    0.000    0.223    0.000 /Users/sp/repos/pymatgen/pymatgen/analysis/phase_diagram.py:488(_get_facet_and_simplex)
    28768    0.038    0.000    0.203    0.000 /Users/sp/repos/pymatgen/pymatgen/util/coord.py:417(in_simplex)
    29711    0.018    0.000    0.118    0.000 /Users/sp/repos/pymatgen/pymatgen/util/coord.py:391(bary_coords)
    59422    0.076    0.000    0.076    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
     2727    0.002    0.000    0.068    0.000 /Users/sp/repos/pymatgen/pymatgen/entries/__init__.py:83(energy_per_atom)
     2727    0.002    0.000    0.065    0.000 /Users/sp/repos/pymatgen/pymatgen/entries/computed_entries.py:368(energy)
     2727    0.003    0.000    0.063    0.000 /Users/sp/repos/pymatgen/pymatgen/entries/computed_entries.py:384(correction)
    29711    0.010    0.000    0.061    0.000 <__array_function__ internals>:2(concatenate)
    28768    0.007    0.000    0.051    0.000 {method 'all' of 'numpy.ndarray' objects}
    28768    0.005    0.000    0.044    0.000 /Users/sp/miniconda3/envs/mavrl/lib/python3.9/site-packages/numpy/core/_methods.py:59(_all)
      943    0.001    0.000    0.042    0.000 /Users/sp/repos/pymatgen/pymatgen/analysis/phase_diagram.py:572(<listcomp>)
    29711    0.009    0.000    0.039    0.000 <__array_function__ internals>:2(dot)
    28768    0.039    0.000    0.039    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     7174    0.022    0.000    0.038    0.000 /Users/sp/miniconda3/envs/mavrl/lib/python3.9/site-packages/uncertainties/core.py:633(f_with_affine_o
```

I enabled and disabled the check, and it made absolutely no difference in the time.

**Comment by shyuep** [comment]
Anyway, I added a check_stable option to get_decomp_and_ehull to the latest commit. If you set that to false, that should allow you to bypass the stability check.

**Comment by CompRhys** [comment]
Thanks, I think you're right that the difference between it being O(N) and O(1) isn't significant unless you're dealing with very large numbers of entries but happy that there's a supported work around.
