### ISSUE TITLE
`LocalStructOrderParams` is not translationally invariant when specifying neighbor indices 

### ISSUE THREAD

**Issue by qai222** [materialsproject/pymatgen#2203]
**Describe the bug**
Values of  `LocalStructOrderParams` change after translating sites when specifying neighbor indices.
Also, IIUC, LSOP thinks this distorted octahedron is similar to a pentagonal pyramid.

**To Reproduce**
```
from pymatgen.analysis.local_env import LocalStructOrderParams
from pymatgen.core.structure import Structure

# a distorted octahedron, there are fractional coords with value <0 or >1
cifstring = """data_primitive
_cell_length_a 8.548
_cell_length_b 9.168
_cell_length_c 12.58
_cell_angle_alpha 89.467
_cell_angle_beta 72.849
_cell_angle_gamma 65.478

_symmetry_space_group_name_H-M 'P 1'
loop_
_space_group_symop_operation_xyz
'x,y,z'

loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
V	0.77756   	0.13214   	0.17138   
O	0.74544   	-0.02747  	0.16792   
O	1.04270   	0.06785   	0.12723   
O	0.78324   	0.18577   	0.01576   
O	0.77380   	0.14078   	0.33290   
O	0.51586   	0.30547   	0.22633   
O	0.74690   	0.40761   	0.19451"""

# before translation
s = Structure.from_str(cifstring, "cif")
los = LocalStructOrderParams(types=["hex_plan_max", "pent_pyr", "oct"])

# if specify neighbor indices
p1 = los.get_order_parameters(s, 0, indices_neighs=[1, 2, 3, 4, 5, 6])
print(p1)
# [0.4477591572605329, 0.5664395961928602, 0.23852499675295133]

# if do not specify
p2 = los.get_order_parameters(s, 0)
print(p2)
# [0.19179211488913345, 0.549512347792701, 0.5197264306316182]

# specify neighbor indices and translate the cluster s.t. it is inside the box
s.translate_sites(list(range(len(s))), vector=(-0.2, 0.2, 0.2))
# los = LocalStructOrderParams(types=["hex_plan_max","pent_pyr", "oct"])
p3 = los.get_order_parameters(s, 0, indices_neighs=[1, 2, 3, 4, 5, 6])
print(p3)
# [0.19179211488913417, 0.5495123477927011, 0.5197264306316184]
```

**Expected behavior**
p1 close to p2 close to p3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2

**Comment by mkhorton** [comment]
@nisse3000 do you have any thoughts on this issue?

**Comment by nisse3000** [comment]
@mkhorton, sure. That looks like a neighbor-finding/image-using "issue". 

If you just print out the distances between the locations of the O neighbors from the V central atom using the "low-fi" index mechanism, you realize that 2 neighbors don't seem to be in the closest image to the V atom because they exhibit distances way larger than 2:

-------------------------------------------------------------------

from pymatgen.core.structure import Structure
cifstring = """data_primitive
_cell_length_a 8.548
_cell_length_b 9.168
_cell_length_c 12.58
_cell_angle_alpha 89.467
_cell_angle_beta 72.849
_cell_angle_gamma 65.478

_symmetry_space_group_name_H-M 'P 1'
loop_
_space_group_symop_operation_xyz
'x,y,z'

loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
V       0.77756         0.13214         0.17138   
O       0.74544         -0.02747        0.16792   
O       1.04270         0.06785         0.12723   
O       0.78324         0.18577         0.01576   
O       0.77380         0.14078         0.33290   
O       0.51586         0.30547         0.22633   
O       0.74690         0.40761         0.19451"""
s = Structure.from_str(cifstring, "cif")
print(s)

Full Formula (V1 O6)
Reduced Formula: VO6
abc   :   8.548000   9.168000  12.580000
angles:  89.467000  72.849000  65.478000
Sites (7)
  #  SP          a        b        c
---  ----  -------  -------  -------
  0  V     0.77756  0.13214  0.17138
  1  O     0.74544  0.97253  0.16792
  2  O     0.0427   0.06785  0.12723
  3  O     0.78324  0.18577  0.01576
  4  O     0.7738   0.14078  0.3329
  5  O     0.51586  0.30547  0.22633
  6  O     0.7469   0.40761  0.19451

import numpy as np
for i in range(1, 7):
    print(np.linalg.norm(s.sites[0].coords - s.sites[i].coords))

7.595027732481124
6.726904760009047
2.005627629286983
2.0244449105916953
2.0408074010602935
2.4394302343682424

-------------------------------------------------------------------

If you, on the other hand, use the standard mechanism for neighbor finding in LocalStructOrderParams, you obtain:

-------------------------------------------------------------------

from pymatgen.analysis.local_env import VoronoiNN
vnn = VoronoiNN(tol=0.0, targets=None)
neighsites = vnn.get_nn(s, 0)
for neighsite in neighsites:
    print(np.linalg.norm(s.sites[0].coords - neighsite.coords))

1.600085415591695
2.4394302343682424
2.0408074010602935
2.005627629286983
1.9867913140898044
2.0244449105916953

-------------------------------------------------------------------

A different image of a neighboring site surrounds a central atom (possibly) in a different manner than the closest image - especially if the cell angles are not 90 degrees. So, that's why @qai222 obtains different OP values between the two "los.get_order_parameters(...)" calls

p1 = los.get_order_parameters(s, 0, indices_neighs=[1, 2, 3, 4, 5, 6])

and

p2 = los.get_order_parameters(s, 0)

Does that make sense?

**Comment by nisse3000** [comment]
Quick addition: the documentation of the "get_order_parameters"-function underscores that "no nearest images of neighbors are determined when providing an index list."

**Comment by qai222** [comment]
Thanks, @nisse3000. If I understand correctly, when `indices_neighs` is provided, the neighbors may not be the image closest to the center atom. Sounds like this can be solved by using `pbc_shortest_vectors`.

A follow-up question: This VO6 unit has "pent_pyr" (0.549) > "oct" (0.519), does this suggest it's more like a pentagonal pyramid than an octahedron? To me, it looks just like a distorted octahedron.

**Comment by nisse3000** [comment]
Welcome, @qai222. Yes, if you want to have it be the closest image, you first have to take care of that manually; that is, before you provide "get_order_parameters" the list of indices. 

Numerically, it should be interpreted that way. However, when you think a bit more about the "rough estimate" character of the order parameters as likelihoods of pattern resemblance scores, you will probably end up concluding that those 2 values are pretty close to each other and that clear cut conclusions are tricky in this area of science. In the end, we are talking about what individual researchers think/perceive as "looking rather like an octahedron than a pentagonal pyramid". To bring that a bit more into perspective: if q_oct would have been 0.9 and q_pent_pyr = 0.5, I believe that most researchers would have interpreted the coordination environment as being a (clear) octahedron rather than a pentagonal pyramid.

**Comment by nisse3000** [comment]
@mkhorton, I get the feeling that the "purported" implementation problems/issues are addressed/do not exist. I believe that we can close the issue.

Is that OK with you, @qai222?

**Comment by qai222** [comment]
Sure, you can close the issue. 

For what it is worth, I end up creating a `Structure` object for the local structure when I need to specify neighbor indices.
