### ISSUE TITLE
hash of sites is not discriminate

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2235]
In #2077 we added a more discriminate hash from `Composition` individual `Site` are effectively `Composition` but they still use the old composition hash. Shall I update the `Site` hash to match composition? I haven't actually traced a slow-down to site matching like I did with compositions but was looking at `Site` code re: #2234 and I feel that if it helps there it will help here also? 

only issue is that the composition hash is salted (as default python hash is salted) whilst the site hash is unsalted therefore would need to remove/change the test on the hash which asserts a value.

@shyamd

**Comment by CompRhys** [comment]
Also a thought re: #2077 currently `Composition({"Fe3+": 2, "O2-":3})` and `Composition({"Fe": 2, "O":3})` have different hashes. I think this is okay but just want to check, I will make a PR to improve the docstring alongside and possible changes to `Site`'s hash

**Comment by shyamd** [comment]
Differing hash methods for different objects is ok, since they're never used across different classes.

That being said, it would be good to update the site hash to be salted. All the hashes should be salted.

**Comment by CompRhys** [comment]
https://github.com/materialsproject/pymatgen/blob/b8b27c6fa3236f032581aa82f668b25a78aa3b57/pymatgen/core/sites.py#L225-L230

The reason I raised it was the potential for the hash collisions we had before where `hash(Composition({"O": 1})) = `hash(Composition({"N": 0.5, "F": 0.5}))` this is much less likely to happen for sites but it **_could_** in principle happen. 

I think I can use the same hash as for `Composition` and then I will sort out the tests so that they don't fail for salted hashes. Any thoughts on the charge assigned species edge case?

https://github.com/materialsproject/pymatgen/blob/b8b27c6fa3236f032581aa82f668b25a78aa3b57/pymatgen/core/composition.py#L236-L240

**Comment by shyamd** [comment]
Hash clashes aren't necessarily a bad thing. Remember hashes are not required to be different for the code to work correctly. That is the job of `__eq__`. Good hashes merely improve performance. If you think improving `Site`'s hash will enable something you need to do, then go for it. 

The salting is important for hashes since they can be a vehicle for security attacks. 

As for charged vs uncharged composition, it's not an issue that the hashes are different for cases where `__eq__` also says they're different. The issue would be if there was ever a situation in which `__eq__` returns `True`, but we got different hashes.

**Comment by shyuep** [comment]
I am fine with making the COmposition Hash use the Site Hash. But @shyamd is correct in that hashes are not meant to be uniquely discriminate. They are meant to be *cheap* and *sufficiently discriminate* to speed up searches. The rule to remember is that equal object must have equal hashes but equal hashes do not mean equal objects.
