### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2348]
Bit annoying that the primary branch is inconsistently named across MP repos. Many still use `master` ([pymatgen](https://github.com/materialsproject/pymatgen), [custodian](https://github.com/materialsproject/custodian), [mapidoc](https://github.com/materialsproject/mapidoc), ...) while some have adopted GitHub's new default `main` ([fireworks](https://github.com/materialsproject/fireworks), [matbench](https://github.com/materialsproject/matbench), [maggma](https://github.com/materialsproject/maggma), ...). Has led me to merge/rebase the wrong branch  on a few occasions. Any chance everything could move to `main`?

**Comment by shyuep** [comment]
It has always been master. It is the other branches that rename themselves to main to serve some woke bullshit. I am not bowing to this kind of crap. You can ask the ones which are called main to go back to master.

**Comment by janosh** [comment]
I agree that dropping the name `master` doesn't actually help with any entrenched societal problems (i.e. the reasoning behind this decision doesn't make much sense) but now it's there and it's even 2 letters shorter so why not use it. 😄

**Comment by shyuep** [comment]
1. The change involves costs. It may be a net benefit to some developers (who work with pymatgen and fireworks etc.) but it is a net negative for me since all my repos are named master. Now I have to spend time renaming all of them. And all the downstream developers have to repull to main. 
2. Because we have to take a stand against this kind of hypersensitive BS that the intolerant left imposes on us. We can always come up with new BS. What if I say as an Asian, I take offense to the color yellow being used for any plots with negative connotations? Should we ban the use of the color or the word yellow then? There is no end to the funny crap we can come up with. 

Incidentally, the word "master" has many meanings. One of them is synonymous with "main". It also means someone with great proficiency or knowledge. The whole argument of master vs main is basically trying to dumb down the English language to the singular historical meaning. People should just move on and deal with problems with practical solutions rather than imposing this kind of nonsense on what I consider free speech.

**Comment by janosh** [comment]
Can't argue with any of your points except one: From my own experience, transitioning from `master` to `main` (on dozens of repos) wasn't much work.

**Comment by janosh** [comment]
One more note: I understand your point that the transition from `master` to `main` is a hassle with no benefits in and of itself. But at least GitHub makes it as smooth as as possible by notifying every fork of upstream default branch changes including instructions what to do about it. This is what I recently got for my pandas fork after they renamed `master` to `main`:

![Screen Shot 2022-01-17 at 15 33 12](https://user-images.githubusercontent.com/30958850/149798727-7393dbe9-c45c-438f-9e15-9b7d35555dec.png)

**Comment by shyuep** [comment]
Well, ease aside, I maintain that principles trump all these considerations. I simply refuse to allow the woke to tell me what to say or think. I am open to reason and logic, not bullshit. So nothing will be done about this. That is the end of this conversation.

**Comment by shyuep** [comment]
I do apologize if I came across as being aggressive. I am aware I can be a bit too direct sometimes. It is just a reaction to a long list of this kind of thing I have to put up with in various fora. I recognize that it is not too difficult to do. But since pymatgen has always been using master, we have decided to keep it as is. Thanks for raising this anyway.

**Comment by mkhorton** [comment]
Thanks for asking about this @janosh, I can offer some perspective about the other codes you mentioned. We had an internal discussion on this issue and ultimately it was left as a decision with the individual package maintainers.

Many of us decided to go ahead and rename to `main` for a few reasons: it was following the [lead of GitHub](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) and [others](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) in the community, the switch itself was painless for us, we wanted to respect [those who feel strongly about this issue](https://betterprogramming.pub/github-replacing-master-with-main-is-a-huge-win-for-inclusion-in-tech-bf517478275b), and there is also an argument that `main` is a better name regardless in the context of distributed version control.

However, there are other factors too, especially for a long-running code where a branch rename might cause a lot of disruption for existing users and, of course, even when weighing all these factors we may reach different conclusions, as demonstrated here -- it's ok for us to disagree.

Ultimately, because it touches on social issues, questions like this are among the most difficult to tackle in open source and in a public forum where it can be difficult to have a nuanced conversation, so I'm grateful for polite discussion on these topics when they happen.

**Comment by janosh** [comment]
Thanks for the thoughtful responses. @shyuep No need to apologize. IMO you raised valid counter points. And like @mkhorton said, disagreements are part of the process.

It was a small concern anyway what the primary branch is called. I'm grateful you guys put so much thought and effort into the tools built around MP. Great thing for the materials community that they're free to use for everyone. 👍
