### ISSUE TITLE
pmg.analysis.structure_matcher.StructureMatcher() primitive_cell setting uses pmg.Structure.find_primitive_structure() without specifying tolerance.

### ISSUE THREAD

**Issue by terencezl** [materialsproject/pymatgen#238]
I had a glimpse of the source code, and realized it uses Structure.find_primitive_structure() with the default precision rather than the args ltol or stol, which is quite large (0.25), and will bend a lot of less symmetric structures to a primitive cell.

**Comment by shyuep** [comment]
@wmdrichards or @sdacek , can you please look into this? Thanks.

**Comment by wmdrichards** [comment]
Do you have a specific case where this is an issue? Choosing default tolerances is kind of tricky, and this tolerance works as desired in almost all instances that I am aware of. You can always avoid calling Structure.find_primitive_structure() by passing primitive_cell=False to the StructureMatcher and making the primitive cells manually.

The tolerance of Structure.find_primitive_structure() is usually much tighter than stol, since stol is scaled by (vol/natoms)**1/3, but the primitive cell tolerance is in angstroms. I guess for artificially low volume structures or when stol is very small this isn't necessarily the case.

**Comment by terencezl** [comment]
Oh. I did not notice that the default tolerance of Structure.get_primitive_structure() refers to Angstrom. 0.25 Å is a reasonable amount.

I guess what I was trying to reach is that since stol controls the atomic position test, it should also be the precision for the primitive cell finding, with the consideration of the scale and proper unit. That way, when the user wants to specify a large/default stol, primitive_cell=True will truly honor the criterion. I don't know if this leads to any side effect, but seems more coherent.

What's the unit of the symprec of Dr. Togo's spglib? I can't seem to find a source. Is it Angstrom too?

**Comment by shyuep** [comment]
The default values are pretty well-tested over the entire ICSD. It should work in most instances. Of course, it all depends on the energy landscape and how likely you are to get stuck in local minima. In general, the tighter the tolerances, the more structures you get and the greater the computational cost, but at the advantage of being less likely to miss out potentially unique structures.

spglib is in Angstroms.

**Comment by shyuep** [comment]
@wmdrichards Maybe you can set primitve tol to == min(stol, 0.25)?

**Comment by shyuep** [comment]
I will close this issue for now, since it is not an particular problem.
