### ISSUE TITLE
Ih point group symmetry operations

### ISSUE THREAD

**Issue by chemyibinjiang** [materialsproject/pymatgen#2428]
I was trying to find out the symmetry operations of the point of Ih. But I did not find a symbol corresponding to it to generate a PointGroup object. 
I would really appreciate the symbol to generate the symmetry operations of Ih point group.

**Comment by shyuep** [comment]
The list of point group symmetry operations in pymatgen are mainly dealing with the crystallographic point groups (Ih is not crystallographic since it has 5-fold rotations). So you will need to look for them in texts. That said, it is relatively easy to generate the whole list if you define the main 5-fold, 3-fold and 2-fold axes using the Operations class and generate the whole list.
