### ISSUE TITLE
PDplotter plotly backend ternary diagram default colors are terrible

### ISSUE THREAD

**Issue by Youjin1985** [materialsproject/pymatgen#2465]
Hi,
Black font on black markers, completely invisible!
![截图_选择区域_20220319162537](https://user-images.githubusercontent.com/93317987/159113854-dc762b32-8f95-4739-81eb-4ed581a9b7ed.png)
 
It's nowhere near publication quality plot, please change default look or allow customisation by arguments of PDPlotter.

**Comment by mkhorton** [comment]
Hi @Youjin1985, please try the matplotlib backend. The 3D ternary plot is intended primarily for _interactive_ use, where the plot can be rotated to allow it to be read more easily, rather than for publication figures.

I am working personally on a 2D version of this plot with the plotly backend, but not sure when I'll finish this. PRs also welcome.
