### ISSUE TITLE
unclear how to retrieve bandstructures

### ISSUE THREAD

**Issue by rkurchin** [materialsproject/pymatgen#2516]
**Describe the bug**
This is not _exactly_ a bug, so much as something I thought was a bug but was actually unclear documentation. 

Basically, I wanted to download entries corresponding to stable materials with nonzero bandgap that have computed bandstructures. I'll describe what I did below...

**To Reproduce**
I want to download entries corresponding to stable materials with nonzero bandgap that have bandstructures computed. 
With the following setup:
```python
from pymatgen.ext.matproj import MPRester
m = MPRester(api_key=api_key)
```

First, I tried:
```python
data = m.query(criteria={"e_above_hull":0, "has_bandstructure":True, "band_gap":{"$gt":0}},
               properties=["full_formula","material_id", #"cif",
                           "elements","band_structure", "band_gap"])
```
This gave me a list of 11700 entries, but most of them seem not to actually have bandstructures, e.g. here's `data[1]`:
```python
{'full_formula': 'Hf2S1N2',
 'material_id': 'mp-1017567',
 'elements': ['Hf', 'N', 'S'],
 'band_structure': None,
 'band_gap': 1.0769000000000002}
```
(spoiler: this turns out to be the correct approach, but in a non-obvious way that I think should be clarified somehow)

So I next changed my query from `"has_bandstructure":True` to instead include `"band_structure":{"$ne":None}`. This gave a much shorter list of 180 entries, and `data[1]` looks like
```python
{'full_formula': 'Mg2U4P4H40O44',
 'material_id': 'mp-1211200',
 'elements': ['H', 'Mg', 'O', 'P', 'U'],
 'band_structure': {'GGA': {'task_id': 'mp-1628661'}},
 'band_gap': 2.4764999999999997}
```
I understood from [the API documentation](https://github.com/materialsproject/mapidoc) that a query for bandstructure wouldn't actually return the bandstructure, but rather a reference to it, which I assume is what that other `mp-XXX` ID is.

So now I try `bs = m.get_bandstructure_by_material_id('mp-1628661')` but I get an `IndexError`. Hmm. Next, I try the `material_id` field and do `bs = m.get_bandstructure_by_material_id('mp-1211200')` but that just returns a `NoneType`.

Initially, I came here to file a "traditional" bug report that this wasn't working, but then I (honestly kind of by accident) tried the `material_id` from `data[1]` in my first query from the longer list, and lo and behold, I got a bandstructure object! Problem solved.

**Expected behavior**
I expected more intuitive names of things and/or documentation of what the names mean. As I said, I did eventually figure out the "correct" way to do what I was trying to do, but it took awhile. While I can understand how `material_id` and `task_id` would be different and thus my first attempt was perhaps nonsensical, I maintain that the inequivalence of the two queries `"has_bandstructure":True` and `"band_structure":{"$ne":None}` can lead to confusion...if lead devs agree, I'm certainly happy to help brainstorm and/or contribute to solutions to this.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 2022.4.26

**Comment by mkhorton** [comment]
Hi @rkurchin, thanks for sharing this experience, this kind of feedback is useful!

One factor here is that you've caught us during a transition period where we're deploying a new API (first major change in 10+ years), which is going to cause some additional confusion since it changes some things, see https://next-gen.materialsproject.org/api for a comparison table between the two -- in particular, be aware that the new API is the one receiving new database updates, and the legacy API is frozen to an older database version, so there may be disagreements between the two.

Some general comments:

* For now, we are still recommending people use the API you're using, but I did want to highlight the new API since this advice may change in the near future. One of the reasons we're developing the new API is to have an opportunity to clear up some points of confusion like this, although the fundamental issue of the difference between `task_id` and `material_id` will remain since this is baked into the database design.

* In the new MPRester, `mpr.get_bandstructure_by_material_id()` should return the bandstructure for either the `material_id` or the `task_id`. For the latter, it will print a warning and the corresponding `material_id`.

* I tried to think what this query would look like in the new API and came up with this:

```
from mp_api import MPRester
from emmet.core.summary import HasProps  # non-obvious import

mpr = MPRester()

docs = mpr.summary.search_summary_docs(
    energy_above_hull=0,
    has_props=[HasProps.bandstructure],
    fields=["material_id"]
)  # returns 64,115 entries, i.e. only those with bandstructure objects


bs = mpr.get_bandstructure_by_material_id(docs[0].material_id)  # retrieve a sample band structure
```

* Based on this example, I would think something that might still confuse new users is the `HasProps` import, so perhaps something for us to think about.

Tagging @munrojm, who's been leading the new API development, in case he wants to comment further or correct me if I've mis-stated anything.

@munrojm, I also noticed another user experience issues which is that querying for a valid `material_id`, but for which a bandstructure object is _not_ available, the error message is perhaps not helpful.

Some more examples from the new API are here: https://next-gen-docs.materialsproject.org/downloading-data/using-the-api/examples

Since this is being developed in a separate repo, if there are follow-up issues related to the new API, they can be posted at https://github.com/materialsproject/api

**Comment by mkhorton** [comment]
Another place to post generate usage questions or feedback about the API is https://matsci.org/materials-project too, which is the more general Materials Project discussion forum.

**Comment by rkurchin** [comment]
Thanks for the detailed reply; this is all useful context and very helpful! I'll poke around with the new API too, looks like there are some exciting and useful improvements!

Also, so noted about the forum as well – I had already debated if this or mapidoc was the right place to file this issue, but seems like that might have been a better option all-around. 😄

**Comment by mkhorton** [comment]
Yes, apologies, there are in some ways too many places to ask questions, and not obvious where the best place might be (and not everyone monitors every venue), so it's really ok to ask questions wherever, and I do my best to route them to the right people when I can!

**Comment by mkhorton** [comment]
I realize I gave an error in my example above too; querying for a zero energy above hull would look like this:

```
docs = mpr.summary.search_summary_docs(
    energy_above_hull=[0, 0],  # this is a range, for a min/max of 0
    has_props=[HasProps.bandstructure],
    fields=["material_id"]
)  # now returns 21,291 entries, i.e. only those with bandstructure objects
```

Correcting for the record.
