### ISSUE TITLE
[FEATURE REQUEST] Python 3.7 support

### ISSUE THREAD

**Issue by sgbaird** [materialsproject/pymatgen#2541]
**Is your feature request related to a problem? Please describe.**
It would be nice to have Python 3.7 support for exposing code examples that depend on `mp_api` on Google Colab. See https://github.com/materialsproject/api/issues/600

**Describe the solution you'd like**
Support for Python 3.7 until Colab starts supporting Python 3.8 directly. https://github.com/googlecolab/colabtools/issues/2165

On Feb 25, 2021, Colab bumped to Python 3.7 despite Python 3.8 available since 2018 https://twitter.com/googlecolab/status/1365062244225060865

**Describe alternatives you've considered**
- [Roundabout hacks to get Python 3.8 installed on Colab](https://stackoverflow.com/a/63797862/13697228)
- Drop Colab as a way to expose top-level code examples when depending on pymatgen

I understand if this isn't in the scope/vision of `pymatgen`, but figured it was worth probing and getting an issue up for added visibility if someone goes looking.

**Comment by shyuep** [comment]
Well, any version of pymatgen pre 2022.X would support python 3.7. Unless you are planning to demo some cutting feature, you can just install one of those? I would say 99% of users do not need the latest version of pymatgen.

**Comment by sgbaird** [comment]
@shyuep thanks for the quick response. An alternative is for me to switch back to the legacy MPRester API which doesn't [depend on a `2022.X` version](https://github.com/materialsproject/api/blob/250f51cade1aead4be6016d1a61329ff1c2ce99b/setup.py#L27). @rkingsbury [suggested I try out the new API](https://matsci.org/t/how-do-i-do-a-time-split-of-materials-project-entries-e-g-pre-2018-vs-post-2018/42584/2?u=sgbaird), which has been cool to see. However, as expected and clearly advertised, the new API is kind of fluid right now with breaking changes flowing (e.g. removal of `query` method, change of kwarg names in `search`), and I'm not sure it will make sense to keep my code compatible with `v0.18.0` (Python 3.7 compatible).

After some trial-and-error with getting `mp_api==0.24.0` installed on Colab, making `mp-api` an optional dependency for [`mp-time-split`](https://github.com/sparks-baird/mp-time-split) (WIP) seems like one of the better options: `pip install mp-time-split[api]` or similar with Python 3.8+ to use the data fetching capabilities rather than simply loading a snapshot from figshare. Seems like a good compromise for my use-case.

**Comment by sgbaird** [comment]
> Made a [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/mp-time-split/blob/main/notebooks/other/mp-api-colab-py38.ipynb) example of running `mp-api`, it takes ~20 minutes, requires kernel restarts, and browser refreshing to get to the first `MPRester` statement and supposedly has to be a copy of that exact notebook due to internal metadata (i.e. can't copy-paste the code to another notebook and have it run) 😅
> 
> The first few statements can be condensed to a single cell of course.

_Originally posted by @sgbaird in https://github.com/materialsproject/api/issues/600#issuecomment-1146678005_

**Comment by shyuep** [comment]
I see. Honestly, I was not aware that there is a separate client for the new API or why it actually needed to be in a separate repository/package. It would have been much easier if that was developed within the existing pymatgen.ext.matproj package and certainly would have far more input from other users/developers. @rkingsbury @mkhorton

**Comment by mkhorton** [comment]
@shyuep please see correspondence dated 01/2022 ("Home of MP API client"). In brief, developing in a separate repo is likely advantageous, but we can certainly re-integrate into pymatgen as an add-on. The main barrier to inclusion is that it would necessitate adding new dependencies to pymatgen, notably `pydantic`, but also potentially others, due to the stricter validation applied in the new API.

@sgbaird we're ultimately following pymatgen version requirements, and from that following the latest numpy version requirements. Ultimately, I would place this on Colab to support newer Python versions; 3.11 is imminent now and is impressively faster, and there have been many quality of life improvements in the intervening versions that would be unfortunate to lose. I think my advice would be two-fold:

1. If there are any problems or bugs with the new MPRester, please continue to post issues in the `api` repo and we will try to get them addressed.
2. If you really need 3.7 support, the API itself is OpenAPI-compliant and has a spec available at https://api.materialsproject.org -- you can continue to make queries directly via `requests` or otherwise.

**Comment by shyuep** [comment]
@mkhorton I am aware that there is a new API under development. What I meant is that I am unclear why it needs to be in a separate package. pydantic is already part of monty since some time ago.

**Comment by janosh** [comment]
> Ultimately, I would place this on Colab to support newer Python versions!

This! Don't understand why it's taking Google so long. py38+ support on Colab has been requested [many times for 2 years now](https://github.com/googlecolab/colabtools/issues/1422).
