### ISSUE TITLE
Inconsistent behavior for calculating charge

### ISSUE THREAD

**Issue by Jeff-oakley** [materialsproject/pymatgen#2837]
**Describe the bug**
The structure.charge function sometimes does not print the right charge

**To Reproduce**
```
from pymatgen.ext.matproj import MPRester
with MPRester("kVbufThFdGlpePa0IbqjnimfyIHc5Ng2") as m:
    # Structure for material id
    str_test = m.get_structure_by_material_id("mp-1138") # learn it online to see what it does

str_test.add_oxidation_state_by_element({'Li':1,'F':-1})
rp_dict2 = {'Li+':{'Li+':0.6,'Mn3+':0.2,'Ti4+':0.2},'F-':{'O2-':0.9,'F-':0.1}}
str3 = str_test.copy()
str3.replace_species(rp_dict2)
print(str3.charge)
```
The charge should be 0.1 but I get 0 as output

**Comment by shyuep** [comment]
A Structure's charge can be different from the sum of the oxidation states (e.g., if you are doing electron or hole doping of the structure).
In this case, the reason is that the API sets the charge. I am not sure why this is the case. @munrojm can you check? As far as I know, MP does not do non-neutral structure computations.
I added a method called `unset_charge` to structure. This sets the charge to None, which ensures that the correct method is called to compute the charge on the fly. I also added a warning when the structure charge is different from the formal sum of oxidation states.

**Comment by munrojm** [comment]
Sorry, a little confused here. Why should the charge be 0.1 in this case? I can confirm that the API simply pulls the charge in directly from the DB and does not change it. As far as I understand, you are correct and we do not do any non-neutral calculations.

**Comment by shyuep** [comment]
He did substitutions. If you sum the oxidation states of the substituted structure, it is 0.1. That is the default behavior if the charge is not set. I am not sure why the charge is set in the API.

**Comment by munrojm** [comment]
Gotcha, I understand now. Looks like the serialized `Structure` objects within the core materials collection have the charge explicitly as zero. Not sure at what point in the pipeline (parsing or running builders) this happens, but it is being set somewhere. We can change this if it conflicts with the expected use in pymatgen and is of big concern.
