### ISSUE TITLE
Can't install on Python 3.11

### ISSUE THREAD

**Issue by adosar** [materialsproject/pymatgen#2849]
I am trying to install pymatgen on a clear virtual environment on Fedora 37.
`python -m venv <virtual-environment-name>`
`source <virtual-environment-name>`
`pip install wheel`
`pip install pymatgen`

But I get the error shown on the attached image.
![Screenshot from 2023-02-19 15-42-18](https://user-images.githubusercontent.com/110358278/219952064-21957890-b5c6-4361-9648-5dea9f20e3c2.png)

**Comment by shyuep** [comment]
3.11 is not officially supported at the moment as it is a bit new. We are working on it.

**Comment by janosh** [comment]
Related issue #2710 and PR #2714

**Comment by adosar** [comment]
Thanks for the information. I would like to add that the same problem was also present on my laptop which runs Fedora 36 (python 3.10).  So, I am guessing that it will be first fixed for 3.10 and then for 3.11?

**Comment by ml-evs** [comment]
> Thanks for the information. I would like to add that the same problem was also present on my laptop which runs Fedora 36 (python 3.10). So, I am guessing that it will be first fixed for 3.10 and then for 3.11?

@adosar in your specific case, it looks like you are using your system Python (i.e., one that comes from Fedora itself) to construct your virtual environment. To get around this issue, you need to install the development version of the Python package for Fedora, with something like `yum install python-dev`. 

This will then allow pip to compile the C-extensions that come with pymatgen (see below that we can also ask that these builds get made in the CI of this package, so that everyone on Linux can just install them without recompiling -- I've had no trouble building these wheels myself of pymatgen for Python 3.11 but as @shyuep suggests there maybe outstanding compatibility issues that I haven't run into). 

*Another option would be to decouple your "science Python" from your system Python by using tools like conda, pyenv etc. to manage separate Python executables for each virtual environment -- people have many opinions on this and the "best tool" changes year on year, so just treat this as something you could consider investigating...*

-----
This has made me notice that currently wheels are not being built for Linux on release. Is this intentional (@shyuep @janosh)?

https://github.com/materialsproject/pymatgen/blob/13a860aab7cbf914c1aaedfa5b06a703211de202/.github/workflows/test.yml#L104

**Comment by janosh** [comment]
> currently wheels are not being built for Linux on release

@ml-evs I noticed this as well but don't know the reason. I assume it's just lack of time to implement. There's an open PR for linux wheels #2800.

**Comment by ml-evs** [comment]
I would've thought that simply adding `ubuntu-latest` to the build matrix line would get you most of the way (that's how I build wheels at least -- understand there must be additional complexities here). It looks like this is what used to be done, until https://github.com/materialsproject/pymatgen/commit/f4959c1a2b6bc1bd744f41888b97383def8d1993

**Comment by adosar** [comment]
For fedora users can do the following:
(Fedora 36 here but of course can work with newer releases)
`dnf install python3.9`
`python3.9 -m venv <venv-name>
`source <venv-name>`
`pip install wheel`
`pip install pymatgen`

Installation had no problems.

**Comment by janosh** [comment]
@ml-evs Ah, [looks like](https://github.com/materialsproject/pymatgen/actions/runs/4248894628/jobs/7388717234#step:4:2501) because of the compiled C extensions in `pymatgen`, uploading a Linux wheel isn't straightforward and [needs to go through `manylinux`](https://stackoverflow.com/a/59586096) like #2800 is attempting.

**Comment by adosar** [comment]
Now `pymatgen` can be easily installed on `python3.10` (work flawlessly in Fedora 36).

**Comment by shyuep** [comment]
Great. Thanks,

**Comment by adosar** [comment]
> Great. Thanks,

@shyuep Haven't tried it yet to `python3.11` though.

**Comment by shyuep** [comment]
Sure.

**Comment by adosar** [comment]
I have tried it also in Fedora 37 with python 3.11.2 and works flawlessly. Just `pip install pymatgen`.

**Comment by janosh** [comment]
@adosar Thanks for confirming.
