### ISSUE TITLE
check vasp ionic convergence based on EDIFFG besides NSW

### ISSUE THREAD

**Issue by mdforti** [materialsproject/pymatgen#2898]
currently convergence of ionic loop of VASP calculation is checked on the number of ionic steps:

https://github.com/materialsproject/pymatgen/blob/89fc2d6f37dd4677e8f861f3227985daf6d3f812/pymatgen/io/vasp/outputs.py#L626

but this is wrong. many times it is possible to stop the ionic loop based i.e. on walltime using STOPCAR and the checker would fail to recognize the convergence at restarting the calculation. 

The convergence should be checked also against EDIFFG. I understand this might get complicated due to EDIFFG might be positive or negative etc.

It is also possible to search  parsing for the string "reached required accuracy" but that is also incomplete, as it is sometimes desirable to change the EDIFF (the string would be present from previous step)

Thank you for considering this feature request!

**Comment by janosh** [comment]
Maybe our resident VASP expert @arosen93 can chime in?

**Comment by arosen93** [comment]
@janosh: This looks fine to me. The `len(final_esteps) < self.parameters["NELM"]` check is the check for the SCF convergence and is unrelated to the "ionic loop" (i.e. relaxation trajectory). The line highlighted is indeed correct for checking that the SCF is converged.

The text below is the relevant data for the ionic convergence.

https://github.com/materialsproject/pymatgen/blob/89fc2d6f37dd4677e8f861f3227985daf6d3f812/pymatgen/io/vasp/outputs.py#L629-L636

That said, it is not clear to me what scenario would exist where convergence is achieved but this condition is not met. @mdforti suggests that it's possible to stop the ionic loop based on the walltime, but by this very definition that implies that the ionic loop has not yet converged (since the user has stopped it manually). I think Pymatgen has to rely on what VASP says is converged and not the user.

**Comment by janosh** [comment]
@arosen93 Thanks for clarifying!

@mdforti I'll close this for now. Feel free re-open with additional details if we missed something.

**Comment by mdforti** [comment]
you are right,

- I  must have made a typo on the first comment, I am referring on cases where ionic relaxation convergence should be tested. 
- I just now see the converged_ionic method, thanks for pointing tho this. 

that said, here is one scenario where  converged_ionic wont work.   I myself run in HPCs with max walltime (i.e. 24 hours), and some structures hard to converge. There should be smarter ways to do this, but I typically run a script which writes a STOPCAR if the run time is close to max walltime, so I get the CHGCAR and the calculation can be restarted easily. then I run another script which relaunches calculations if necessary. This implies checking weather the forces are converged or not, because the number of ionic steps will always be smaller than NSW.

I understand now this might not be general enough, and actually this is already solved for me on my side. 

Thank you all to look at this.
