### ISSUE TITLE
Key error of io.CifParser.parse_magmoms

### ISSUE THREAD

**Issue by fyangtcmp** [materialsproject/pymatgen#2904]
I notice the static method `parse_magmoms` in class `CifParser` use the keys such as
- `_atom_site_moment_label`
- `_atom_site_moment_crystalaxis_x`
to parse atomic magnetic moments.

But the mcif files in MAGNDATA(<http://webbdcrista1.ehu.es/magndata/>), a large database with more than 2000 published magnetic structures, use the keys such as 
- `_atom_site_moment.label`
- `_atom_site_moment.crystalaxis_x`.

It is a dot, not an underline, after the string '_atom_site_moment'. So `parse_magmoms` is not compatible with this mcif format.

**Comment by mkhorton** [comment]
Yes, this was intentional, but I'm adding a note here to explain: the magCIF standard was a working standard, with many magCIF files "in the wild" prior to the standard being finalised. During this process, some of the keys changed, so there are two supported notations for this field, and the current pymatgen parser looks like it uses the older standard.

The canonical field names are defined by the IUCr, see here: https://www.iucr.org/__data/iucr/cifdic_html/3/MAGNETIC_CIF/index.html

The action here will probably be to update pymatgen to support both.
