### ISSUE TITLE
Merge `ElementBase` into `Element`?

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2999]
@shyuep Should we merge `ElementBase` into `Element`? It says `ElementBase` has no enum values so it can be subclassed but it isn't actually subclassed anywhere in `pymatgen`. Seems cleaner to only have an `Element` class.

https://github.com/materialsproject/pymatgen/blob/3d4d160941edc47d26b21457c792187256f55886/pymatgen/core/periodic_table.py#L30-L33

**Comment by mkhorton** [comment]
Why was `ElementBase` created to start with, presumably for good reason? I vaguely remember this, can try and find the PR.

**Comment by janosh** [comment]
Here's the PR: https://github.com/materialsproject/pymatgen/pull/2005

It also lists subclasses as the reason for creating `ElementBase`.

**Comment by mkhorton** [comment]
I see the mention for API use. Perhaps it was used to define a class for intercalant elements?

**Comment by jmmshn** [comment]
I think it was to get nested as_dict / from_dict to work properly.   So the problem was that all the classes in emmet that had these classes required very custom construction and I wanted to have a a definition of these classes that behaved more like dataclasses so serialization was less troublesome.  There were many times where the objects serialized only when they were top level.
