### ISSUE TITLE
POSCAR is ignoring selective dynamics

### ISSUE THREAD

**Issue by SelfMade2001** [materialsproject/pymatgen#3008]
I am using the pymatgen.io.vasp.inputs Module. According to the documentation (https://pymatgen.org/pymatgen.io.vasp.inputs.html) the from_file(filename) method of the Poscar class should handle selective dynamics. However it does ignore selective dynamics or read it in the wrong way.

Here is some test file called POSCAR_test:

```
Test
   1.000000000
    20.0000000000000000    0.0000000000000000    0.0000000000000000
     0.0000000000000000   23.0000000000000000    0.0000000000000000
     0.0000000000000000    0.0000000000000000   15.0000000000000000
   C     H  
   2     1
Selective dynamics
Cartesian
     2.201545747940     2.214990562232     1.000000000000  T  T  T  
     3.625859708182     2.193941473662     1.000000000000  T  T  T  
     4.326973622066     3.379594386626     1.000000000000  T  T  T  
```

Here is the code:

```
from pymatgen.io.vasp.inputs import Poscar
poscar = Poscar.from_file('POSCAR_test', False, False)
print(poscar)
```

The output:

```
Test
1.0
  20.0000000000000000    0.0000000000000000    0.0000000000000000
   0.0000000000000000   23.0000000000000000    0.0000000000000000
   0.0000000000000000    0.0000000000000000   15.0000000000000000
C H
2 1
direct
   0.1100772873970000    0.0963039374883478    0.0666666666666667 C
   0.1812929854091000    0.0953887597244348    0.0666666666666667 C
   0.2163486811033000    0.1469388863750435    0.0666666666666667 H
```

As you can see, selective dynamics are getting ignored, which should not be the case.

If you change the POSCAR_test to this:

```
Test
   1.000000000
    20.0000000000000000    0.0000000000000000    0.0000000000000000
     0.0000000000000000   23.0000000000000000    0.0000000000000000
     0.0000000000000000    0.0000000000000000   15.0000000000000000
   C     H  
   2     1
Selective dynamics
Cartesian
     2.201545747940     2.214990562232     1.000000000000 C T  T  T  
     3.625859708182     2.193941473662     1.000000000000 C T  T  T  
     4.326973622066     3.379594386626     1.000000000000 H T  T  T  
```

The output will be this:

```
Test
1.0
  20.0000000000000000    0.0000000000000000    0.0000000000000000
   0.0000000000000000   23.0000000000000000    0.0000000000000000
   0.0000000000000000    0.0000000000000000   15.0000000000000000
C H
2 1
Selective dynamics
direct
   0.1100772873970000    0.0963039374883478    0.0666666666666667 F T T C
   0.1812929854091000    0.0953887597244348    0.0666666666666667 F T T C
   0.2163486811033000    0.1469388863750435    0.0666666666666667 F T T H
```

Now the module seems to get that I want to use selective dynamics, but it sets all the x-coordinates to F and not T.

I also tried this POSCAR_test:

```
Test
   1.000000000
    20.0000000000000000    0.0000000000000000    0.0000000000000000
     0.0000000000000000   23.0000000000000000    0.0000000000000000
     0.0000000000000000    0.0000000000000000   15.0000000000000000
   C     H  
   2     1
Selective dynamics
Cartesian
     2.201545747940     2.214990562232     1.000000000000 T  T  T  C 
     3.625859708182     2.193941473662     1.000000000000 T  T  T  C
     4.326973622066     3.379594386626     1.000000000000 T  T  T  H
```

which outputs the same as the first POSCAR_test, totally ignoring selective dynamics.

**Comment by esoteric-ephemera** [comment]
Hey @SelfMade2001, the purpose of selective dynamics is to enable only certain degrees of freedom during relaxations. If you enable selective dynamics, but allow all degrees of freedom to relax, as in your first example, then selective dynamics is not used. That's why pymatgen ignores it

If that's unclear, please [see the VASP manual page on this](https://www.vasp.at/wiki/index.php/POSCAR#Full_format_specification)

In your second example, the ordering of selective dynamics tags and labels for the atomic sites is incorrect, the correct format is:

> Test
   1.000000000
    20.0000000000000000    0.0000000000000000    0.0000000000000000
     0.0000000000000000   23.0000000000000000    0.0000000000000000
     0.0000000000000000    0.0000000000000000   15.0000000000000000
   C     H  
   2     1
Selective dynamics
Cartesian
     2.201545747940     2.214990562232     1.000000000000 T  T  T  C
     3.625859708182     2.193941473662     1.000000000000 T  T  T  C
     4.326973622066     3.379594386626     1.000000000000 T  T  T  H
     
But again, selective dynamics won't be enabled since all sites have all degrees of freedom permitted to relax.

The reason you're getting gobbled output from pymatgen is because the elemental symbols are misplaced in the last three lines, and it expects any of the strings `("T", "True", "F", "False")` to appear where the elemental symbols appear.
