### ISSUE TITLE
Release 2023.6.28 on PyPI is incomplete

### ISSUE THREAD

**Issue by mrakitin** [materialsproject/pymatgen#3134]
#### Description

There is only one wheel file available for v2023.6.28 on PyPI (`pymatgen-2023.6.28-cp39-cp39-macosx_11_0_arm64.whl`). All other versions are missing: the wheels for Linux, macOS, and Windows (Python 3.8-3.11) at https://pypi.org/project/pymatgen/2023.6.28/#files:

![image](https://github.com/materialsproject/pymatgen/assets/13209176/7231dea3-65d5-45f8-ae0a-e1e2f4483740)

#### Repro

Go to https://pypi.org/project/pymatgen/2023.6.28/#files, and check the list of wheel files.

#### Expected behavior

Same set of wheel files for various platforms as at https://pypi.org/project/pymatgen/2023.6.23/#files:

![image](https://github.com/materialsproject/pymatgen/assets/13209176/10ab6b29-4ef2-4e04-8532-bdde2e1a6793)

#### Environment

Relevant versions and platform info:

- PyPI, v2023.6.28

**Comment by janosh** [comment]
There's a [newer release out now that's sound](https://pypi.org/project/pymatgen/2023.7.11/#files). I guess we could delete the old partial release but not sure if that creates more problems than it solves. Usually you deprecate a broken release rather than delete but looks like PyPI doesn't have a deprecation feature.

Either way would have to be done by @shyuep.

**Comment by shyuep** [comment]
I yanked the 2023.6.28 version. This should be now solved.

**Comment by mrakitin** [comment]
Thank you, @shyuep!
