### ISSUE TITLE
returning matplotlib.pyplot module in plotting methods

### ISSUE THREAD

**Issue by lbluque** [materialsproject/pymatgen#3138]
#### Description

This may be more a clarification than a bug necessarily.

I have noticed that many of the plotting methods using the `matplotlib` backend return the `matplotlib.pyplot` module.
For example in the [phase diagram plotter](https://github.com/materialsproject/pymatgen/blob/9f0c7c28fee6681058dadbaafd2b2b52a0f9e251/pymatgen/analysis/phase_diagram.py#L3719) or this general [pretty_plot](https://github.com/materialsproject/pymatgen/blob/9f0c7c28fee6681058dadbaafd2b2b52a0f9e251/pymatgen/util/plotting.py#L63) function.

#### Expected behavior

 I am confused by this design choice since it is not particularly helpful to return the `plt` module.

Would it be more appropriate to to return the `Figure` object? Though users can access get it by using `plt.gca` it makes more sense to me, and seems to parallel the `go.Figure` object returned when using the `plotly` backend in plotting methods.

**Comment by shyuep** [comment]
I don't think this was a design choice per se. The general idea was to return an object that would allow `show` to be called and for some basic testing of the plot generation code. I have no problems with changing it to returning a Figure object.

The plotly backend came much later and so is a bit more coherent in design.

**Comment by arosen93** [comment]
Agreed that this behavior is generally counter-intuitive for new users (and myself whenever I revisit the phase diagram plotter...).

**Comment by shyuep** [comment]
Yes pls go ahead.

**Comment by janosh** [comment]
> I can draft up a PR changing the return values from `plt` to `Figure` throughout pymatgen.

That would be great! I think that makes much more sense. It's how [`pymatviz`](https://github.com/janosh/pymatviz) does it as well.

**Comment by lbluque** [comment]
> > I can draft up a PR changing the return values from `plt` to `Figure` throughout pymatgen.
> 
> That would be great! I think that makes much more sense. It's how [`pymatviz`](https://github.com/janosh/pymatviz) does it as well.
> 
> Would be a breaking change thought so should be highlighted in the change log and release notes.

@janosh thanks for pointing me to `pymatviz`!  I noticed you return `Axes`  in the matplotlib functions there, instead of `Figure`. Maybe that makes more sense because the`Axes` object is what actually has the plot attributes (lines, legend, labels, etc). One can always get the `Figure` from the `Axes`, but the reverse can be ambiguous if the Figure has multiple axes.

Any thoughts? I like the design of pymatviz functions with the optional Axes argument and always returning the Axes where the plot was drawn.

In all cases, it will likely be a breaking change but one that is "easy" to adjust to, but perhaps with noticeable effects on projects using `pymatgen` plotting functions.

**Comment by JaGeo** [comment]
It would potentially break 100s of projects, scripts. (😬) Mine included.

**Comment by shyuep** [comment]
@JaGeo Why would it break any scripts? I am assuming most people call show() after getting the plt.

**Comment by JaGeo** [comment]
@shyuep switching to Figure is completely fine, agreed.

**Comment by janosh** [comment]
@lbluque I think returning the `axes` object is even better from an API design standpoint (for the reasons you mentioned, `Axes` is what actually changes and what you interact most with when making plots) but it would break more existing code. `figure` and the `plt` module share at least some of their interface (e.g. `.show()` as @shyuep mentioned). But even that is not backwards compatible in every way.

@shyuep Re breakage, people might call

```py
from pymatgen import SomePlotter

plt = SomePlotter().get_plot()
plt.ylabel("some custom ylabel")
```

this no longer works if we return `fig` instead of `plt`.

@JaGeo We might be able to workout a script that you point at some directory and that at least adds a `TODO` comment to every line of code that might have been broken by this change. I still think this is enough of an API improvement to warrant the effort.

**Comment by lbluque** [comment]
Thanks so much for getting this done @janosh !

**Comment by goodwilling** [comment]
> It would potentially break 100s of projects, scripts. (😬) Mine included.

Sorry to open this issue again. In our project updated to latest pymatgen, we encounter unexpected errors in various scripts customizing the window title and size after using get_plot().  After updating all the scripts according to the above breaking changes,  we still get the following error:  

Traceback (most recent call last):

.../pymatgen/electronic_structure/plotter.py", line 711, in fix_layout
    ax.gcf().tight_layout()
    ^^^^^^
AttributeError: 'Axes' object has no attribute 'gcf'

This error seems to be due to Line 711/712 in pymatgen/electronic_structure/plotter.py:

        def fix_layout(event):
            if (event.name == "key_press_event" and event.key == "t") or event.name == "resize_event":
                ax.gcf().tight_layout()
                ax.gcf().canvas.draw()

since ax is now an Axes object, not a pyplot object.

**Comment by goodwilling** [comment]
Sorry to bother again. The BSPlotter.plot_brillouin() seems to not work after the breaking changes.  I wonder what the reason of this problem is.  The following is the script and result. Thanks. 

python
>>> from pymatgen.ext.matproj import MPRester
>>> mpr = MPRester("32-digit key")
>>> bs = mpr.get_bandstructure_by_material_id("mp-3748")
Retrieving ElectronicStructureDoc documents: 100%|███████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
>>> from pymatgen.electronic_structure.plotter import BSPlotter
>>> plotter = BSPlotter(bs)
>>> plotter.plot_brillouin()

Result: an empty window comes out.
