### ISSUE TITLE
MP2020Compatibility not applying correct anion correction

### ISSUE THREAD

**Issue by BowenD-UCB** [materialsproject/pymatgen#3425]
Version: 2023.10.11

```
from pymatgen.entries.compatibility import MaterialsProject2020Compatibility
from pymatgen.entries.computed_entries import ComputedStructureEntry

params = {"hubbards": {"Mn": 3.9, "O": 0, "Li": 0}, "run_type": "GGA+U"}

cse = ComputedStructureEntry(lmo, vasp_raw_energy, parameters=params)
MaterialsProject2020Compatibility(check_potcar=False).process_entries(cse)
```

<img width="655" alt="Screen Shot 2023-10-25 at 9 33 54 PM" src="https://github.com/materialsproject/pymatgen/assets/84425382/166c95d3-7718-4376-b10e-c659c9378314">

The anion correction is missing for these O2-

**Comment by BowenD-UCB** [comment]
Code from [here](https://github.com/CederGroupHub/chgnet/blob/main/examples/fine_tuning.ipynb)

**Comment by shyuep** [comment]
@janosh @kristinpersson  feel free to tag whoever is supposed to be dealing with this in MP.

**Comment by janosh** [comment]
@shyuep The person to tag would be @rkingsbury or myself. I thought I fixed this problem in https://github.com/materialsproject/pymatgen/pull/3184 but looks like there's another bug related to `Composition` indexing using `Elements`/`str` vs. `Species`. Currently:

```py
comp = Composition({"Li+": 2, "Mn3+": 2, "O2-": 4})
comp["Li"] == 0
```

I would argue `comp["Li"]` should return 2 instead, i.e. return all species with matching symbol, regardless of oxidation state. That would fix the problem @BowenD-UCB encountered since currently `comp["O"]` returns 0 and so no oxide correction is applied.

But this would be breaking in the (rarely used) case of `allow_negative=True` since e.g. currently

```py
comp = Composition({"Mg": 1, "Mg2+": -1})
comp["Mg"] == 1
```

which would change to return 1.

**Comment by shyuep** [comment]
I think it is fine for you to handle it for now. But a more permanent person in charge needs to be defined.
