### ISSUE TITLE
Elastic and NMR OUTCAR needs to be refactored

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#350]
## System

* Pymatgen version: master

## Summary

* Currently, the Outcar __init__ is a big mess with elastic property and NMR reading all bundled in. Note that OUTCAR parsing is by nature very calculation dependent. We cannot cater to ALL kinds of run in the __init__ method. Hence, other than the most basic parameters like energies and magmoms, all other special parsing should be done via the read_*property* methods, with the use of read_pattern as a general approach.
* @montoyjh Pls refactor the elastic and piezo parsing.
* @xhqu1981 Pls refactor the NMR parsing.

Thanks.

**Comment by xhqu1981** [comment]
Will do. Thanks.

**Comment by shyuep** [comment]
@montoyjh @xhqu1981 Can I have a status update pls.

**Comment by xhqu1981** [comment]
I will push the solution tonight or tomorrow.

**Comment by xhqu1981** [comment]
Done. @shyuep I have to add the read_table_pattern() method. This is because the NMR data are tables and context related. Very hard to defined by a single line pattern. E.g. the chemical shift table have two sections one is without core contribution, another is with core contributions. Only the second one is desired. The rows from both section are matching exactly the same line pattern. As such, I have to add one more function read_table_pattern(). Both chemical shift and EFG parsing are built on it. Concept of of named and unamed regex capturing groups is involved. It increases some complexity, however, it helps users to get the desired field only.

**Comment by montoyjh** [comment]
The read_table_pattern is a lot more flexible than my initial approach to the elastic/piezo, so I'm going to redo my changes using that method.

**Comment by xhqu1981** [comment]
@montoyjh Thanks.

**Comment by shyuep** [comment]
Thanks,
