### ISSUE TITLE
Breaking behavior: Removal of `pymatgen.io.vasp.sets.get_vasp_outcar` without warning

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3988]
### Python version

3.11

### Pymatgen version

pymatgen 2024.8.8

### Current behavior

```python
from pymatgen.io.vasp.sets import get_vasp_outcar
```

The above used to work on pymatgen < 2024.8.8 but does not exist any longer in pymatgen >= 2024.8.8. I don't believe there was a deprecation warning, so it may break other people's codes as-is.

### Expected Behavior

A deprecation warning before removal.

**Comment by shyuep** [comment]
This has been fixed with the 2024.8.9 emergency release.

**Comment by Andrew-S-Rosen** [comment]
Thank you!

**Comment by janosh** [comment]
@shyuep please unrevert my #3865 PR. just add back the 
`get_vasprun_outcar` function that was accidentally dropped during merge conflict resolution which I might add was unnecessarily confusing because you moved everything to a `src` layout after i opened #3865. the reason it wasn't already merged before you [pointlessly moved all those files](https://github.com/materialsproject/pymatgen/issues/3874#issue-2344184349) (for which btw you never asked my or @mkhorton's approval either) is because [you asked](https://github.com/materialsproject/pymatgen/pull/3835#issuecomment-2118103809) that i do it after https://github.com/materialsproject/pymatgen/pull/3835 which was sensible so i did.

the split of several-thousand-line files is an obvious improvement. you're throwing away my time by undoing that work

in https://github.com/materialsproject/pymatgen/pull/3989 [you write](https://github.com/materialsproject/pymatgen/pull/3989#issue-2458280210)

> I did not agree to this.

what's that supposed to mean? there are hundreds of PRs that you don't agree to. if every one of those required your explicit approval, pymatgen development would grind to a standstill

**Comment by mkhorton** [comment]
I think we should re-open #3865 and more comprehensively test.

It's a good idea to split these files up for maintainability. This can be done without backwards-incompatible changes; it seems like `get_vasprun_outcar` was an oversight.

However, I would go further than #3865. The `pymatgen.io.vasp.outputs` and `pymatgen.io.vasp.inputs` could also be split up into new folders without introducing backwards incompatibility, and just to improve ease-of-navigation. This would mean, e.g. `pymatgen.io.vasp.inputs.potcar` etc. Like the `/src` change, this sort of change does not need to introduce any breakage.

To be specific `pymatgen.io.vasp.inputs` is currently 2932 LOC, `.outputs` is 5363 LOC and `.sets` is 3205 LOC. While having long files is not in itself an error, it does makes things more difficult than necessary.
