### ISSUE TITLE
Different gaps from Vasprun.eigenvalue_band_properties and Bandstructure.get_band_gap()

### ISSUE THREAD

**Issue by blondegeek** [materialsproject/pymatgen#455]
Hello,

I get very different band gaps from Vasprun.eigenvalue_band_properties and Bandstructure.get_band_gap(). The former gives a gap of 1.3011 while the other 0. This seems to be because the maximum valence band is above the fermi level but still has some electron occupation.

```
vrun = Vasprun('vasprun.xml')
(gap, cbm, vbm, is_direct) = vrun.eigenvalue_band_properties
gap
>>1.3011
bs = vrun.get_band_structure()
bs.get_band_gap()
>>{u'direct': False, u'energy': 0.0, u'transition': None}
vrun.efermi
>>1.71998034
```

I've attached a zipped copy of the vasprun.xml.
[vasprun.zip](https://github.com/materialsproject/pymatgen/files/452773/vasprun.zip)

Thanks!
Tess

**Comment by computron** [comment]
Note - i don't think the vbm is listed in the above output, but it was above the Fermi level (I think something on the order of 1.85?)

**Comment by shyuep** [comment]
Assigned to @hautierg

**Comment by hautierg** [comment]
The two methods define differently what is the band gap.
The eigenvalue_band_properties looks at occupations. Here there are partial occupations of your upper bands. Therefore this depends on the smearing you use.
The Bandstructure.get_band_gap() looks at bands above and below fermi level. Here there are bands crossing the fermi level. So the method considers it as a metal and gives you a zero band gap.
I would stress though that if you want to have an accurate band gap determination you should not rely on a relaxation run (it looks like this is a relaxation run) but instead use a dense k-point grid (with a non-self-consistent run if you want) on a static run. This k-point grid can be uniform or on specific paths. The k-point meshes for relaxation is usually way too coarse to give an accurate estimate of the band gap.

**Comment by computron** [comment]
Ok

I agree that in my experience, get_band_structure().get_band_gap() works better. I used that method when coding MatMethods parsers, etc.

My issue is that this is not really documented anywhere. To give an example, someone external was recently trying to code a FireTask that checked the band gap, and if it was less than a threshold value, to defuse the rest of the workflow. That person had no idea what was the difference between eigenvalue_band_properties and get_band_gap and used the former one (anyway, that is one directly part of Vasprun). This caused erroneous results as many of their jobs ended up not being defused even though they were metallic systems due to the problems in eigenvalue_band_properties that you describe. It is very difficult for an outside user to know how to use these methods properly.

**Comment by computron** [comment]
Btw the "agree that get_band_gap is more reliable" comes from an email that @hautierg wrote me but isn't reflected in this chain
