### ISSUE TITLE
fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by gmatteo** [materialsproject/pymatgen#496]
We are trying to merge merge pymatgen/master 
in our branches but git refuses to merge with the following error:

 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories

If I look at the history, I see that the commits before  Sep 25, 2016 now
have two different ids e.g.

```
Merge branch 'master' of github.com:materialsproject/pymatgen  …
Former-commit-id: 948c455b573851b2e89ed83a784c8b0fa788bc99 [formerly 5842306]
Former-commit-id: b149932fa3eecf656d194b87bc4111b73e45c4b0
```

See:
https://github.com/materialsproject/pymatgen/commit/3895853c7f2b4c5a6c89e9c785ea8644d7d841ef

It seems that something changed in the history and git refuses to merge because of that.
github now says that my branch is: 11434 commits ahead, 11509 commits behind materialsproject:master and similar messages are found in the forks of many other developers. 

Any idea on what's happening and what could have caused this?

Best,
Matteo

**Comment by shyuep** [comment]
Recently, we hit the limit for Github repo sizes on pymatgen because of all the large test files. I had to do a history cleanup. Please make a copy of your existing pyamtgen repo, refork pymatgen, reclone pymatgen, and copy your new changes (I am guessing only files in the pymatgen package directory) over to the new repo. Do a recommit.
