### ISSUE TITLE
git push error on LFP_CHGCAR.gz

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#514]
Hello

I download and update a fresh version of pymatgen (last commit 15 november). I just forked the repository. But if I tried to push commits on my own repository I got the following error :

```
open /Users/gvallver/git/pymatgen/test_files/path_finder/LFP_CHGCAR: no such file or directory
error: failed to push some refs to 'https://github.com/gVallverdu/pymatgen.git'
```

Actually, the CHGCAR file is zipped both on the remote and my local system.

Thanks
system : OS X 10.11
git version 2.7.4 (Apple Git-66)

**Comment by shyuep** [comment]
You just reforked? If not, pls delete your fork (making sure you still have your own local copy). Then refork, reclone, add whatever changes you need and push.

I had to rebase the git branches because the total repo size is close to the Github limit. Unfortunately, that means the git history is no longer consistent with local copies.

**Comment by gVallverdu** [comment]
Ok, I do a new clone and copy my changes. Now it works fine. 
The pull request should come soon :)
Thanks
