### ISSUE TITLE
git complaining about missing file

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#563]
I'm trying to make a (temporarily private) development fork of pymatgen on github to share code with colleagues, but get errors related to `git lfs`:

`[531e5b64ee126c2e0fba128fd0317662f36cbf02f651610ba085ba4354b96c6f] Object does not exist on the server: [404] Object does not exist on the server`

I think it's related to this PR: https://github.com/materialsproject/pymatgen/pull/459/files

It looks like the LFP_CHGCAR was committed, but then deleted and replaced with LFP_CHGCAR.gz, and this is causing the error?

Was following the instructions given here https://help.github.com/articles/duplicating-a-repository/ since github doesn't allow private forks of public repos.

**Comment by shyuep** [comment]
If you want to make a private repo of pymatgen, you need to clone the current version. Then create the private repo on github and clone that. Move the files from the clone to the private repo, and push it. The error you are seeing is probably due to the rebasing of pymatgen done a few months back. I suggest you clone a fresh version.
