### ISSUE TITLE
bug in latest pymatgen

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#633]
## System

* Pymatgen version: master
* Python version: 2.7
* OS version: mac

## Summary

* See example code

## Example code

```python
from pymatgen.analysis.elasticity.elastic import *
```

## Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/analysis/elasticity/__init__.py", line 7, in <module>
    from .elastic import *
  File "/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/analysis/elasticity/elastic.py", line 747, in <module>
    v_diff = np.vectorize(sp.diff)
NameError: name 'sp' is not defined
```

## Suggested solution (if any)

* not sure what the intention is of the error-creating code, so no suggestions

**Comment by computron** [comment]
(note - if you don't like the ``import *``, just do ``from pymatgen.analysis.elasticity.elastic import ElasticTensor`` and you get the same error)

**Comment by montoyjh** [comment]
Ah, I failed to protect a sympy-dependent section of the new code with the
conditional.  I'll fix shortly.

**Comment by shyuep** [comment]
Why is there a dependence on sympy?

**Comment by shyuep** [comment]
If sympy is really needed, we can just add it to dependency. It is not that large.

**Comment by montoyjh** [comment]
Just FYI, sympy is being used to determine the pseudoinverse expression in
the higher order fitting scheme, which requires a symbolic derivative (this
enables a lot more flexibility in handling different stress/strain inputs
for fitting).  I'm working on a refactor that doesn't require sympy, since
it's by far the slowest piece of the procudure, but it's convenient to have
the symbolic option.
